blank_issues_enabled: false
contact_links:
- name: ❓ GitHub Discussions (Q&A / Assistenza)
  url: https://github.com/PiBOH/flowonline2/discussions/
  about: Utilizza la sezione Discussions per domande, Q&A e assistenza generale / Use GitHub Discussions for Q&A, general support, and discussing ideas.
