import { Statement } from '../types/flow';

export class CodeGenerator {
  public static generate(statements: Statement[], language: 'python' | 'cpp' | 'java' | 'javascript' | 'csharp'): string {
    switch (language) {
      case 'python':
        return this.toPython(statements);
      case 'cpp':
        return this.toCpp(statements);
      case 'java':
        return this.toJava(statements);
      case 'javascript':
        return this.toJavaScript(statements);
      case 'csharp':
        return this.toCSharp(statements);
    }
  }

  // PYTHON GENERATOR
  private static toPython(statements: Statement[], indent = ''): string {
    if (statements.length === 0) return `${indent}pass\n`;
    let code = '';
    
    // Add imports or boilerplate at top-level
    const isTopLevel = indent === '';
    if (isTopLevel) {
      code += `# Generated by Flowonline2 (developed by PiBOH, MIT License)\n`;
      code += `import math\n\n`;
      code += `def main():\n`;
      indent = '    ';
    }

    for (const stmt of statements) {
      if (stmt.comment) {
        code += `${indent}# ${stmt.comment}\n`;
      }

      switch (stmt.type) {
        case 'declare':
          if (stmt.isArray) {
            code += `${indent}${stmt.variableName} = [None] * int(${this.exprToPython(stmt.arraySize)})\n`;
          } else {
            // Python doesn't require explicit declaration, but initializing is clean
            const initVal = stmt.variableType === 'Integer' || stmt.variableType === 'Real' ? '0' : stmt.variableType === 'Boolean' ? 'False' : '""';
            code += `${indent}${stmt.variableName} = ${initVal}  # type: ${stmt.variableType}\n`;
          }
          break;

        case 'assign':
          code += `${indent}${stmt.variableName} = ${this.exprToPython(stmt.expression)}\n`;
          break;

        case 'input':
          code += `${indent}${stmt.variableName} = input("Enter ${stmt.variableName}: ")\n`;
          // Optional conversion block
          break;

        case 'output':
          const endStr = stmt.newline ? '' : ', end=""';
          code += `${indent}print(${this.exprToPython(stmt.expression)}${endStr})\n`;
          break;

        case 'if':
          code += `${indent}if ${this.exprToPython(stmt.condition)}:\n`;
          code += this.toPython(stmt.thenBranch, indent + '    ');
          if (stmt.elseBranch.length > 0) {
            code += `${indent}else:\n`;
            code += this.toPython(stmt.elseBranch, indent + '    ');
          }
          break;

        case 'while':
          code += `${indent}while ${this.exprToPython(stmt.condition)}:\n`;
          code += this.toPython(stmt.body, indent + '    ');
          break;

        case 'for':
          const stepVal = stmt.stepValue ? this.exprToPython(stmt.stepValue) : '1';
          const sign = stmt.direction === 'dec' ? '-' : '';
          const endAdjust = stmt.direction === 'dec' ? '- 1' : '+ 1';
          code += `${indent}for ${stmt.variableName} in range(${this.exprToPython(stmt.startValue)}, ${this.exprToPython(stmt.endValue)} ${endAdjust}, ${sign}${stepVal}):\n`;
          code += this.toPython(stmt.body, indent + '    ');
          break;

        case 'do':
          // Python doesn't have a direct do-while, simulate with infinite loop + break
          code += `${indent}while True:\n`;
          code += this.toPython(stmt.body, indent + '    ');
          code += `${indent}    if not (${this.exprToPython(stmt.condition)}):\n`;
          code += `${indent}        break\n`;
          break;

        case 'call':
          const args = stmt.arguments ? stmt.arguments : '';
          code += `${indent}${stmt.functionName}(${args})\n`;
          break;

        case 'comment':
          code += `${indent}# ${stmt.text}\n`;
          break;
      }
    }

    if (isTopLevel) {
      code += `\nif __name__ == "__main__":\n    main()\n`;
    }

    return code;
  }

  private static exprToPython(expr: string): string {
    return expr
      .replace(/&&/g, ' and ')
      .replace(/\|\|/g, ' or ')
      .replace(/!/g, ' not ')
      .replace(/&/g, ' + ') // String concatenation
      .replace(/abs\(/gi, 'abs(')
      .replace(/sin\(/gi, 'math.sin(')
      .replace(/cos\(/gi, 'math.cos(')
      .replace(/sqrt\(/gi, 'math.sqrt(')
      .replace(/pi/gi, 'math.pi');
  }

  // JAVASCRIPT GENERATOR
  private static toJavaScript(statements: Statement[], indent = ''): string {
    let code = '';
    const isTopLevel = indent === '';
    if (isTopLevel) {
      code += `// Generated by Flowonline2 (developed by PiBOH, MIT License)\n\n`;
      code += `function main() {\n`;
      indent = '    ';
    }

    for (const stmt of statements) {
      if (stmt.comment) {
        code += `${indent}// ${stmt.comment}\n`;
      }

      switch (stmt.type) {
        case 'declare':
          if (stmt.isArray) {
            code += `${indent}let ${stmt.variableName} = new Array(${this.exprToJs(stmt.arraySize)}).fill(null);\n`;
          } else {
            const initVal = stmt.variableType === 'Integer' || stmt.variableType === 'Real' ? '0' : stmt.variableType === 'Boolean' ? 'false' : '""';
            code += `${indent}let ${stmt.variableName} = ${initVal}; // type: ${stmt.variableType}\n`;
          }
          break;

        case 'assign':
          code += `${indent}${stmt.variableName} = ${this.exprToJs(stmt.expression)};\n`;
          break;

        case 'input':
          code += `${indent}${stmt.variableName} = prompt("Enter ${stmt.variableName}:");\n`;
          break;

        case 'output':
          if (stmt.newline) {
            code += `${indent}console.log(${this.exprToJs(stmt.expression)});\n`;
          } else {
            code += `${indent}process.stdout.write(String(${this.exprToJs(stmt.expression)}));\n`;
          }
          break;

        case 'if':
          code += `${indent}if (${this.exprToJs(stmt.condition)}) {\n`;
          code += this.toJavaScript(stmt.thenBranch, indent + '    ');
          code += `${indent}} else {\n`;
          code += this.toJavaScript(stmt.elseBranch, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'while':
          code += `${indent}while (${this.exprToJs(stmt.condition)}) {\n`;
          code += this.toJavaScript(stmt.body, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'for':
          const step = stmt.stepValue ? this.exprToJs(stmt.stepValue) : '1';
          const op = stmt.direction === 'dec' ? '>=' : '<=';
          const update = stmt.direction === 'dec' ? `-= ${step}` : `+= ${step}`;
          code += `${indent}for (${stmt.variableName} = ${this.exprToJs(stmt.startValue)}; ${stmt.variableName} ${op} ${this.exprToJs(stmt.endValue)}; ${stmt.variableName} ${update}) {\n`;
          code += this.toJavaScript(stmt.body, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'do':
          code += `${indent}do {\n`;
          code += this.toJavaScript(stmt.body, indent + '    ');
          code += `${indent}} while (${this.exprToJs(stmt.condition)});\n`;
          break;

        case 'call':
          code += `${indent}${stmt.functionName}(${stmt.arguments || ''});\n`;
          break;

        case 'comment':
          code += `${indent}// ${stmt.text}\n`;
          break;
      }
    }

    if (isTopLevel) {
      code += `}\n\nmain();\n`;
    }

    return code;
  }

  private static exprToJs(expr: string): string {
    return expr
      .replace(/&/g, ' + ') // concat operator
      .replace(/pi/gi, 'Math.PI')
      .replace(/abs\(/gi, 'Math.abs(')
      .replace(/sin\(/gi, 'Math.sin(')
      .replace(/cos\(/gi, 'Math.cos(')
      .replace(/sqrt\(/gi, 'Math.sqrt(');
  }

  // C++ GENERATOR
  private static toCpp(statements: Statement[], indent = ''): string {
    let code = '';
    const isTopLevel = indent === '';
    if (isTopLevel) {
      code += `// Generated by Flowonline2 (developed by PiBOH, MIT License)\n`;
      code += `#include <iostream>\n`;
      code += `#include <string>\n`;
      code += `#include <cmath>\n`;
      code += `#include <vector>\n\n`;
      code += `using namespace std;\n\n`;
      code += `int main() {\n`;
      indent = '    ';
    }

    for (const stmt of statements) {
      if (stmt.comment) {
        code += `${indent}// ${stmt.comment}\n`;
      }

      switch (stmt.type) {
        case 'declare':
          const cppType = this.toCppType(stmt.variableType);
          if (stmt.isArray) {
            code += `${indent}vector<${cppType}> ${stmt.variableName}(${this.exprToCpp(stmt.arraySize)});\n`;
          } else {
            code += `${indent}${cppType} ${stmt.variableName};\n`;
          }
          break;

        case 'assign':
          code += `${indent}${stmt.variableName} = ${this.exprToCpp(stmt.expression)};\n`;
          break;

        case 'input':
          code += `${indent}cin >> ${stmt.variableName};\n`;
          break;

        case 'output':
          const nl = stmt.newline ? ' << endl' : '';
          code += `${indent}cout << ${this.exprToCpp(stmt.expression)}${nl};\n`;
          break;

        case 'if':
          code += `${indent}if (${this.exprToCpp(stmt.condition)}) {\n`;
          code += this.toCpp(stmt.thenBranch, indent + '    ');
          code += `${indent}} else {\n`;
          code += this.toCpp(stmt.elseBranch, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'while':
          code += `${indent}while (${this.exprToCpp(stmt.condition)}) {\n`;
          code += this.toCpp(stmt.body, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'for':
          const step = stmt.stepValue ? this.exprToCpp(stmt.stepValue) : '1';
          const op = stmt.direction === 'dec' ? '>=' : '<=';
          const update = stmt.direction === 'dec' ? `-= ${step}` : `+= ${step}`;
          code += `${indent}for (${stmt.variableName} = ${this.exprToCpp(stmt.startValue)}; ${stmt.variableName} ${op} ${this.exprToCpp(stmt.endValue)}; ${stmt.variableName} ${update}) {\n`;
          code += this.toCpp(stmt.body, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'do':
          code += `${indent}do {\n`;
          code += this.toCpp(stmt.body, indent + '    ');
          code += `${indent}} while (${this.exprToCpp(stmt.condition)});\n`;
          break;

        case 'call':
          code += `${indent}${stmt.functionName}(${stmt.arguments || ''});\n`;
          break;

        case 'comment':
          code += `${indent}// ${stmt.text}\n`;
          break;
      }
    }

    if (isTopLevel) {
      code += `    return 0;\n`;
      code += `}\n`;
    }

    return code;
  }

  private static toCppType(type: string): string {
    switch (type) {
      case 'Integer': return 'int';
      case 'Real': return 'double';
      case 'String': return 'string';
      case 'Boolean': return 'bool';
      default: return 'double';
    }
  }

  private static exprToCpp(expr: string): string {
    return expr
      .replace(/&/g, ' + ')
      .replace(/pi/gi, 'M_PI')
      .replace(/abs\(/gi, 'abs(')
      .replace(/sin\(/gi, 'sin(')
      .replace(/cos\(/gi, 'cos(')
      .replace(/sqrt\(/gi, 'sqrt(');
  }

  // JAVA GENERATOR
  private static toJava(statements: Statement[], indent = ''): string {
    let code = '';
    const isTopLevel = indent === '';
    if (isTopLevel) {
      code += `// Generated by Flowonline2 (developed by PiBOH, MIT License)\n`;
      code += `import java.util.Scanner;\n\n`;
      code += `public class Program {\n`;
      code += `    private static Scanner input = new Scanner(System.in);\n\n`;
      code += `    public static void main(String[] args) {\n`;
      indent = '        ';
    }

    for (const stmt of statements) {
      if (stmt.comment) {
        code += `${indent}// ${stmt.comment}\n`;
      }

      switch (stmt.type) {
        case 'declare':
          const jType = this.toJavaType(stmt.variableType);
          if (stmt.isArray) {
            code += `${indent}${jType}[] ${stmt.variableName} = new ${jType}[${this.exprToJava(stmt.arraySize)}];\n`;
          } else {
            const initVal = stmt.variableType === 'Integer' || stmt.variableType === 'Real' ? '0' : stmt.variableType === 'Boolean' ? 'false' : '""';
            code += `${indent}${jType} ${stmt.variableName} = ${initVal};\n`;
          }
          break;

        case 'assign':
          code += `${indent}${stmt.variableName} = ${this.exprToJava(stmt.expression)};\n`;
          break;

        case 'input':
          // Pick appropriate scanner method
          code += `${indent}${stmt.variableName} = input.next(); // user should parse as necessary\n`;
          break;

        case 'output':
          const printMethod = stmt.newline ? 'println' : 'print';
          code += `${indent}System.out.${printMethod}(${this.exprToJava(stmt.expression)});\n`;
          break;

        case 'if':
          code += `${indent}if (${this.exprToJava(stmt.condition)}) {\n`;
          code += this.toJava(stmt.thenBranch, indent + '    ');
          code += `${indent}} else {\n`;
          code += this.toJava(stmt.elseBranch, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'while':
          code += `${indent}while (${this.exprToJava(stmt.condition)}) {\n`;
          code += this.toJava(stmt.body, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'for':
          const step = stmt.stepValue ? this.exprToJava(stmt.stepValue) : '1';
          const op = stmt.direction === 'dec' ? '>=' : '<=';
          const update = stmt.direction === 'dec' ? `-= ${step}` : `+= ${step}`;
          code += `${indent}for (${stmt.variableName} = ${this.exprToJava(stmt.startValue)}; ${stmt.variableName} ${op} ${this.exprToJava(stmt.endValue)}; ${stmt.variableName} ${update}) {\n`;
          code += this.toJava(stmt.body, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'do':
          code += `${indent}do {\n`;
          code += this.toJava(stmt.body, indent + '    ');
          code += `${indent}} while (${this.exprToJava(stmt.condition)});\n`;
          break;

        case 'call':
          code += `${indent}${stmt.functionName}(${stmt.arguments || ''});\n`;
          break;

        case 'comment':
          code += `${indent}// ${stmt.text}\n`;
          break;
      }
    }

    if (isTopLevel) {
      code += `    }\n`;
      code += `}\n`;
    }

    return code;
  }

  private static toJavaType(type: string): string {
    switch (type) {
      case 'Integer': return 'int';
      case 'Real': return 'double';
      case 'String': return 'String';
      case 'Boolean': return 'boolean';
      default: return 'double';
    }
  }

  private static exprToJava(expr: string): string {
    return expr
      .replace(/&/g, ' + ')
      .replace(/pi/gi, 'Math.PI')
      .replace(/abs\(/gi, 'Math.abs(')
      .replace(/sin\(/gi, 'Math.sin(')
      .replace(/cos\(/gi, 'Math.cos(')
      .replace(/sqrt\(/gi, 'Math.sqrt(');
  }

  // C# GENERATOR
  private static toCSharp(statements: Statement[], indent = ''): string {
    let code = '';
    const isTopLevel = indent === '';
    if (isTopLevel) {
      code += `// Generated by Flowonline2 (developed by PiBOH, MIT License)\n`;
      code += `using System;\n\n`;
      code += `public class Program {\n`;
      code += `    public static void Main(string[] args) {\n`;
      indent = '        ';
    }

    for (const stmt of statements) {
      if (stmt.comment) {
        code += `${indent}// ${stmt.comment}\n`;
      }

      switch (stmt.type) {
        case 'declare':
          const csType = this.toCSharpType(stmt.variableType);
          if (stmt.isArray) {
            code += `${indent}${csType}[] ${stmt.variableName} = new ${csType}[${this.exprToCSharp(stmt.arraySize)}];\n`;
          } else {
            const initVal = stmt.variableType === 'Integer' || stmt.variableType === 'Real' ? '0' : stmt.variableType === 'Boolean' ? 'false' : '""';
            code += `${indent}${csType} ${stmt.variableName} = ${initVal};\n`;
          }
          break;

        case 'assign':
          code += `${indent}${stmt.variableName} = ${this.exprToCSharp(stmt.expression)};\n`;
          break;

        case 'input':
          code += `${indent}${stmt.variableName} = Console.ReadLine(); // parse manually as needed\n`;
          break;

        case 'output':
          const printMethod = stmt.newline ? 'WriteLine' : 'Write';
          code += `${indent}Console.${printMethod}(${this.exprToCSharp(stmt.expression)});\n`;
          break;

        case 'if':
          code += `${indent}if (${this.exprToCSharp(stmt.condition)}) {\n`;
          code += this.toCSharp(stmt.thenBranch, indent + '    ');
          code += `${indent}} else {\n`;
          code += this.toCSharp(stmt.elseBranch, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'while':
          code += `${indent}while (${this.exprToCSharp(stmt.condition)}) {\n`;
          code += this.toCSharp(stmt.body, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'for':
          const step = stmt.stepValue ? this.exprToCSharp(stmt.stepValue) : '1';
          const op = stmt.direction === 'dec' ? '>=' : '<=';
          const update = stmt.direction === 'dec' ? `-= ${step}` : `+= ${step}`;
          code += `${indent}for (${stmt.variableName} = ${this.exprToCSharp(stmt.startValue)}; ${stmt.variableName} ${op} ${this.exprToCSharp(stmt.endValue)}; ${stmt.variableName} ${update}) {\n`;
          code += this.toCSharp(stmt.body, indent + '    ');
          code += `${indent}}\n`;
          break;

        case 'do':
          code += `${indent}do {\n`;
          code += this.toCSharp(stmt.body, indent + '    ');
          code += `${indent}} while (${this.exprToCSharp(stmt.condition)});\n`;
          break;

        case 'call':
          code += `${indent}${stmt.functionName}(${stmt.arguments || ''});\n`;
          break;

        case 'comment':
          code += `${indent}// ${stmt.text}\n`;
          break;
      }
    }

    if (isTopLevel) {
      code += `    }\n`;
      code += `}\n`;
    }

    return code;
  }

  private static toCSharpType(type: string): string {
    switch (type) {
      case 'Integer': return 'int';
      case 'Real': return 'double';
      case 'String': return 'string';
      case 'Boolean': return 'bool';
      default: return 'double';
    }
  }

  private static exprToCSharp(expr: string): string {
    return expr
      .replace(/&/g, ' + ')
      .replace(/pi/gi, 'Math.PI')
      .replace(/abs\(/gi, 'Math.Abs(')
      .replace(/sin\(/gi, 'Math.Sin(')
      .replace(/cos\(/gi, 'Math.Cos(')
      .replace(/sqrt\(/gi, 'Math.Sqrt(');
  }
}
