import { Statement, VariableType } from '../types/flow';

/**
 * Data driven source-code generators.
 *
 * Every language is described by a small "profile" of templates instead of a
 * hand written recursive function, which is what makes it possible to ship the
 * full Flowgorithm language list (~33 targets) without 33 copies of the same
 * tree walker.
 *
 * Templates use @tokens:
 *   @name @type @expr @cond @init @size @start @end @step @args @text @declarations
 */

export interface LangProfile {
  id: string;
  label: string;

  indent: string; // one nesting level
  bodyIndent: string; // extra indent applied to the whole program body
  comment: string; // single line comment template
  header: string; // may contain @declarations
  footer: string;
  emptyBody: string; // emitted when a block body would be empty ('' = nothing)

  // Declarations must be moved to the top of the program (Pascal, Ada, Fortran)
  hoistDeclarations: boolean;
  hoistPreamble: string; // e.g. 'var'

  declare: string;
  declareArray: string;
  assign: string;
  input: string;
  /** Optional per-type read templates (used when a language must cast the input) */
  inputTypes?: Partial<Record<VariableType, string>>;
  output: string;
  outputNoNewline: string;
  /**
   * True when the closing template of a block belongs entirely INSIDE the
   * block (indentation sensitive languages such as Nim).
   */
  closeIndentAll?: boolean;

  ifOpen: string;
  ifElse: string;
  ifClose: string;

  whileOpen: string;
  whileClose: string;

  forOpen: string;
  forOpenDesc: string;
  forClose: string;

  doOpen: string;
  doClose: string;

  call: string;

  types: Record<VariableType, string>;
  init: Record<VariableType, string>;

  varPrefix: string; // '$', '@' (Perl/PHP/PowerShell/Transact-SQL)
  quote: '"' | "'"; // string literal delimiter used by the language
  mathPrefix: string;
  funcs: Partial<Record<string, string>>; // canonical lowercase name -> emitted name
  pi: string;

  and: string;
  or: string;
  not: string;
  concat: string;
  eq: string; // '==' or '=' (only '==' triggers the '=' -> '==' rewriting)
}

const MATH_FUNCS = ['abs', 'sin', 'cos', 'tan', 'sqrt', 'log', 'exp', 'floor', 'ceil', 'round'];

// Words that must never receive a variable prefix (Perl/PHP/PowerShell/T-SQL)
const RESERVED = new Set([
  'true', 'false', 'null', 'nil', 'none', 'and', 'or', 'not', 'mod', 'div', 'rem', 'new',
  'abs', 'sin', 'cos', 'tan', 'sqrt', 'log', 'exp', 'floor', 'ceil', 'round', 'pi', 'e',
  'str', 'int', 'real', 'bool', 'boolean', 'string', 'math', 'php_eol', 'select', 'from',
  'where', 'declare', 'set', 'print', 'begin', 'end', 'case', 'if', 'then', 'else'
]);

// ── Shared defaults (C-like family) ──────────────────────────────────────────
const CLike: Omit<LangProfile, 'id' | 'label'> = {
  indent: '    ',
  bodyIndent: '',
  comment: '// @text',
  header: '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
  footer: '',
  emptyBody: '',
  hoistDeclarations: false,
  hoistPreamble: '',
  declare: '@type @name = @init;',
  declareArray: '@type[] @name = new @type[@size];',
  assign: '@name = @expr;',
  input: '@name = Console.ReadLine();',
  output: 'Console.WriteLine(@expr);',
  outputNoNewline: 'Console.Write(@expr);',
  ifOpen: 'if (@cond) {',
  ifElse: '} else {',
  ifClose: '}',
  whileOpen: 'while (@cond) {',
  whileClose: '}',
  forOpen: 'for (@name = @start; @name <= @end; @name += @step) {',
  forOpenDesc: 'for (@name = @start; @name >= @end; @name -= @step) {',
  forClose: '}',
  doOpen: 'do {',
  doClose: '} while (@cond);',
  call: '@name(@args);',
  types: { Integer: 'int', Real: 'double', String: 'string', Boolean: 'bool' },
  init: { Integer: '0', Real: '0', String: '""', Boolean: 'false' },
  varPrefix: '',
  quote: '"',
  mathPrefix: '',
  funcs: {},
  pi: '3.14159265358979',
  and: ' && ',
  or: ' || ',
  not: '!',
  concat: ' + ',
  eq: '=='
};

// Small helpers to build profiles that share a family
const std = (
  overrides: Partial<LangProfile> & {
    indent?: string;
    comment?: string;
    assign?: string;
    call?: string;
    and?: string;
    or?: string;
    not?: string;
    concat?: string;
    eq?: string;
    types?: Record<VariableType, string>;
    init?: Record<VariableType, string>;
    funcs?: Partial<Record<string, string>>;
    pi?: string;
    mathPrefix?: string;
    varPrefix?: string;
    quote?: '"' | "'";
    declare?: string;
    declareArray?: string;
    input?: string;
    output?: string;
    outputNoNewline?: string;
    ifOpen?: string;
    ifElse?: string;
    ifClose?: string;
    whileOpen?: string;
    whileClose?: string;
    forOpen?: string;
    forOpenDesc?: string;
    forClose?: string;
    doOpen?: string;
    doClose?: string;
    indent2?: string;
    header?: string;
    footer?: string;
    bodyIndent?: string;
    emptyBody?: string;
    hoistDeclarations?: boolean;
    hoistPreamble?: string;
  }
) => overrides;

// ── Template filling ─────────────────────────────────────────────────────────
const fill = (template: string, vars: Record<string, string>): string => {
  let out = template;
  const keys = Object.keys(vars).sort((a, b) => b.length - a.length);
  for (const key of keys) {
    out = out.split(`@${key}`).join(vars[key]);
  }
  return out;
};

const indentText = (text: string, indent: string): string =>
  text
    .split('\n')
    .map((line) => (line.length > 0 ? indent + line : line))
    .join('\n');

// ── Expression conversion ────────────────────────────────────────────────────
const doubleEquals = (expr: string): string => {
  let out = '';
  for (let i = 0; i < expr.length; i++) {
    const c = expr[i];
    if (c === '=') {
      const prev = expr[i - 1];
      const next = expr[i + 1];
      const isComparison =
        prev === '<' || prev === '>' || prev === '=' || prev === '!' || next === '=';
      out += isComparison ? '=' : '==';
    } else {
      out += c;
    }
  }
  return out;
};

/** Adds the language variable prefix ($x, @x ...) to every identifier. */
const prefixIdentifiers = (expr: string, prefix: string): string => {
  let out = '';
  let i = 0;
  while (i < expr.length) {
    const c = expr[i];

    // string literals are copied verbatim
    if (c === '"' || c === "'") {
      const quote = c;
      out += c;
      i++;
      while (i < expr.length && expr[i] !== quote) {
        out += expr[i];
        i++;
      }
      if (i < expr.length) {
        out += expr[i];
        i++;
      }
      continue;
    }

    if (/[A-Za-z_]/.test(c)) {
      let j = i;
      while (j < expr.length && /[A-Za-z0-9_]/.test(expr[j])) j++;
      const word = expr.slice(i, j);
      const next = expr[j];
      // function calls (word(), members (word.x) and language keywords stay untouched
      const keepAsIs =
        RESERVED.has(word.toLowerCase()) ||
        next === '(' ||
        next === '.';
      out += keepAsIs ? word : prefix + word;
      i = j;
      continue;
    }

    out += c;
    i++;
  }
  return out;
};

/**
 * String literals must survive every operator rewrite untouched, and be
 * re-quoted for languages that do not use Flowgorithm's double quotes.
 */
const protectStrings = (expr: string, quote: string) => {
  const literals: string[] = [];
  const out = expr.replace(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/g, (match) => {
    const inner = match.slice(1, -1);
    literals.push(quote === '"' ? match : `'${inner}'`);
    return `\u0002${literals.length - 1}\u0002`;
  });
  return {
    out,
    restore: (text: string) =>
      text.replace(/\u0002(\d+)\u0002/g, (_, index: string) => literals[Number(index)])
  };
};

const convertExpr = (raw: string, p: LangProfile): string => {
  let expr = (raw ?? '').trim();
  if (!expr) return '';

  // literals are hidden first, restored as the very last step
  const { out: masked, restore } = protectStrings(expr, p.quote);
  expr = masked;

  if (p.varPrefix) expr = prefixIdentifiers(expr, p.varPrefix);

  // logical operators: the whitespace around them is swallowed so that the
  // profile values (' and ', ' -and ') do not produce double spaces
  const AND = '\u0001AND\u0001';
  const OR = '\u0001OR\u0001';
  expr = expr.replace(/\s*&&\s*/g, AND).replace(/\s*\|\|\s*/g, OR);
  expr = expr.replace(/\s*!(?!=)/g, p.not.trim() === '!' ? '!' : ` ${p.not}`);
  if (p.eq !== '=') expr = doubleEquals(expr);
  expr = expr.replace(/\s*&/g, p.concat);

  for (const fn of MATH_FUNCS) {
    const target = p.funcs[fn] ?? `${p.mathPrefix}${fn}`;
    expr = expr.replace(new RegExp(`\\b${fn}\\s*\\(`, 'gi'), `${target}(`);
  }
  expr = expr.replace(/\bpi\b/gi, p.pi);

  expr = expr.replace(new RegExp(AND, 'g'), p.and).replace(new RegExp(OR, 'g'), p.or);
  // string literals are still masked here, so squeezing spaces is safe
  expr = expr.replace(/[ \t]{2,}/g, ' ');
  return restore(expr).trim();
};

// ── Statement emission ───────────────────────────────────────────────────────
const declareVars = (stmt: Extract<Statement, { type: 'declare' }>, p: LangProfile) => ({
  type: p.types[stmt.variableType],
  name: `${p.varPrefix}${stmt.variableName}`,
  init: p.init[stmt.variableType],
  size: convertExpr(stmt.arraySize, p)
});

const collectVarTypes = (list: Statement[], map: Map<string, VariableType>): void => {
  for (const stmt of list) {
    if (stmt.type === 'declare') map.set(stmt.variableName, stmt.variableType);
    else if (stmt.type === 'if') {
      collectVarTypes(stmt.thenBranch, map);
      collectVarTypes(stmt.elseBranch, map);
    } else if (stmt.type === 'while' || stmt.type === 'for' || stmt.type === 'do') {
      collectVarTypes(stmt.body, map);
    }
  }
};

const collectDeclares = (list: Statement[], out: Extract<Statement, { type: 'declare' }>[]): void => {
  for (const stmt of list) {
    if (stmt.type === 'declare') out.push(stmt);
    else if (stmt.type === 'if') {
      collectDeclares(stmt.thenBranch, out);
      collectDeclares(stmt.elseBranch, out);
    } else if (stmt.type === 'while' || stmt.type === 'for' || stmt.type === 'do') {
      collectDeclares(stmt.body, out);
    }
  }
};

const genList = (
  list: Statement[],
  p: LangProfile,
  indent: string,
  varTypes: Map<string, VariableType>
): string => {
  const out: string[] = [];

  // Every chunk is flushed through indentText, so multi line templates
  // (Pascal "if ... then\nbegin", T-SQL "IF ...\nBEGIN", ...) stay aligned.
  const emit = (template: string, vars: Record<string, string> = {}) => {
    if (!template) return;
    out.push(indentText(fill(template, vars), indent));
  };

  // Closing templates ('} while (...)', 'LOOP WHILE ...', 'until ...') may be
  // multi line: everything but the last line still belongs INSIDE the block.
  const emitClose = (template: string, vars: Record<string, string> = {}) => {
    if (!template) return;
    const parts = fill(template, vars).split('\n');
    const dedentLast = !p.closeIndentAll;
    const last = dedentLast ? (parts.pop() as string) : '';
    const head = parts.map((line) => (line ? p.indent + line : line)).join('\n');
    out.push(indentText(head ? `${head}${last ? `\n${last}` : ''}` : last, indent));
  };

  const block = (statements: Statement[]): string => {
    const body = genList(statements, p, indent + p.indent, varTypes);
    if (body) return body;
    return p.emptyBody ? indentText(p.emptyBody, indent + p.indent) : '';
  };

  for (const stmt of list) {
    if (stmt.comment) emit(p.comment, { text: stmt.comment });

    switch (stmt.type) {
      case 'declare':
        if (p.hoistDeclarations) break;
        emit(stmt.isArray ? p.declareArray : p.declare, declareVars(stmt, p));
        break;

      case 'assign':
        emit(p.assign, {
          name: `${p.varPrefix}${stmt.variableName}`,
          expr: convertExpr(stmt.expression, p)
        });
        break;

      case 'input': {
        // the type of an input block comes from its declare block
        const type = varTypes.get(stmt.variableName) ?? 'String';
        emit(p.inputTypes?.[type] ?? p.input, {
          name: `${p.varPrefix}${stmt.variableName}`,
          type: p.types[type]
        });
        break;
      }

      case 'output':
        emit(stmt.newline ? p.output : p.outputNoNewline, {
          expr: convertExpr(stmt.expression, p)
        });
        break;

      case 'if': {
        emit(p.ifOpen, { cond: convertExpr(stmt.condition, p) });
        const thenBody = block(stmt.thenBranch);
        if (thenBody) out.push(thenBody);
        if (stmt.elseBranch.length > 0) {
          emit(p.ifElse);
          const elseBody = block(stmt.elseBranch);
          if (elseBody) out.push(elseBody);
        }
        emit(p.ifClose);
        break;
      }

      case 'while': {
        emit(p.whileOpen, { cond: convertExpr(stmt.condition, p) });
        const body = block(stmt.body);
        if (body) out.push(body);
        emitClose(p.whileClose);
        break;
      }

      case 'for': {
        const template = stmt.direction === 'dec' ? p.forOpenDesc : p.forOpen;
        emit(template, {
          name: `${p.varPrefix}${stmt.variableName}`,
          type: p.types.Integer,
          init: p.init.Integer,
          start: convertExpr(stmt.startValue, p),
          end: convertExpr(stmt.endValue, p),
          step: stmt.stepValue ? convertExpr(stmt.stepValue, p) : '1'
        });
        const body = block(stmt.body);
        if (body) out.push(body);
        emitClose(p.forClose, {
          name: `${p.varPrefix}${stmt.variableName}`,
          step: stmt.stepValue ? convertExpr(stmt.stepValue, p) : '1'
        });
        break;
      }

      case 'do': {
        emit(p.doOpen);
        const body = block(stmt.body);
        if (body) out.push(body);
        emitClose(p.doClose, { cond: convertExpr(stmt.condition, p) });
        break;
      }

      case 'call':
        emit(p.call, {
          name: stmt.functionName,
          args: stmt.arguments ? stmt.arguments.split(',').map((a) => convertExpr(a, p)).join(', ') : ''
        });
        break;

      case 'comment':
        emit(p.comment, { text: stmt.text });
        break;
    }
  }

  return out.join('\n');
};

/** Generates a full program in the language described by `p`. */
export function generateWithProfile(statements: Statement[], p: LangProfile): string {
  const hoisted: Extract<Statement, { type: 'declare' }>[] = [];
  if (p.hoistDeclarations) collectDeclares(statements, hoisted);

  const declText = hoisted
    .map((d) => indentText(fill(d.isArray ? p.declareArray : p.declare, declareVars(d, p)), p.bodyIndent))
    .join('\n');

  const declarations = declText
    ? [p.hoistPreamble, declText].filter(Boolean).join('\n')
    : '';

  const varTypes = new Map<string, VariableType>();
  collectVarTypes(statements, varTypes);

  const header = fill(p.header, { declarations });
  const body = genList(statements, p, p.bodyIndent, varTypes);
  const footer = fill(p.footer, {});

  return [header, body, footer].filter((part) => part !== '').join('\n') + '\n';
}

export const toProfile = (
  id: string,
  label: string,
  overrides: Parameters<typeof std>[0]
): LangProfile => ({ ...CLike, ...std(overrides), id, label });

// ── The Flowgorithm language list ────────────────────────────────────────────
// (imported generators of the legacy languages live in codeGenerator.ts)
export const PROFILES: Record<string, LangProfile> = {
  ada: toProfile('ada', 'Ada 95', {
    indent: '   ',
    bodyIndent: '   ',
    comment: '-- @text',
    header: [
      '-- Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
      'with Ada.Text_IO; use Ada.Text_IO;',
      'with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;',
      'with Ada.Float_Text_IO; use Ada.Float_Text_IO;',
      'with Ada.Numerics.Elementary_Functions; use Ada.Numerics.Elementary_Functions;',
      '',
      'procedure Main is',
      '@declarations',
      'begin'
    ].join('\n'),
    footer: 'end Main;',
    hoistDeclarations: true,
    declare: '@name : @type := @init;',
    declareArray: '@name : array (1 .. @size) of @type;',
    assign: '@name := @expr;',
    input: 'Get (@name);',
    output: 'Put_Line (@expr);',
    outputNoNewline: 'Put (@expr);',
    ifOpen: 'if @cond then',
    ifElse: 'else',
    ifClose: 'end if;',
    whileOpen: 'while @cond loop',
    whileClose: 'end loop;',
    forOpen: 'for @name in @start .. @end loop',
    forOpenDesc: 'for @name in reverse @start .. @end loop',
    forClose: 'end loop;',
    doOpen: 'loop',
    doClose: 'exit when @cond;\nend loop;',
    call: '@name (@args);',
    types: { Integer: 'Integer', Real: 'Float', String: 'String', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0.0', String: '""', Boolean: 'False' },
    pi: 'Ada.Numerics.Pi',
    and: ' and ',
    or: ' or ',
    not: 'not ',
    concat: ' & ',
    eq: '=',
    funcs: { sqrt: 'Sqrt', sin: 'Sin', cos: 'Cos', tan: 'Tan', log: 'Log', exp: 'Exp', abs: 'abs' }
  }),

  applescript: toProfile('applescript', 'AppleScript', {
    indent: '    ',
    comment: '-- @text',
    header: '-- Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: 'set @name to @init',
    declareArray: 'set @name to {}',
    assign: 'set @name to @expr',
    input: 'set @name to text returned of (display dialog "Enter @name" default answer "")',
    output: 'display dialog (@expr)',
    outputNoNewline: 'log (@expr)',
    ifOpen: 'if (@cond) then',
    ifElse: 'else',
    ifClose: 'end if',
    whileOpen: 'repeat while (@cond)',
    whileClose: 'end repeat',
    forOpen: 'repeat with @name from @start to @end',
    forOpenDesc: 'repeat with @name from @start to @end by -1',
    forClose: 'end repeat',
    doOpen: 'repeat',
    doClose: 'if not (@cond) then exit repeat\nend repeat',
    call: '@name(@args)',
    types: { Integer: 'integer', Real: 'real', String: 'text', Boolean: 'boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'false' },
    pi: 'pi',
    and: ' and ',
    or: ' or ',
    not: 'not ',
    concat: ' & ',
    eq: '='
  }),

  autohotkey: toProfile('autohotkey', 'AutoHotKey', {
    indent: '    ',
    comment: '; @text',
    header: '; Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)\n#NoEnv\n#SingleInstance force',
    declare: '@name := @init',
    declareArray: '@name := []',
    assign: '@name := @expr',
    input: 'InputBox, @name, Flowonline2, Enter @name',
    output: 'MsgBox, % @expr',
    outputNoNewline: 'FileAppend, % @expr, *',
    ifOpen: 'if (@cond) {',
    ifElse: '} else {',
    ifClose: '}',
    whileOpen: 'while (@cond) {',
    whileClose: '}',
    forOpen: '@name := @start\nwhile (@name <= @end) {',
    forOpenDesc: '@name := @start\nwhile (@name >= @end) {',
    forClose: '@name += @step\n}',
    doOpen: 'loop {',
    doClose: '} until !(@cond)',
    call: '@name(@args)',
    types: { Integer: 'Integer', Real: 'Float', String: 'String', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'false' },
    pi: '3.14159265358979',
    and: ' && ',
    or: ' || ',
    not: '!',
    concat: ' . ',
    eq: '=',
    funcs: {
      abs: 'Abs', sin: 'Sin', cos: 'Cos', tan: 'Tan', sqrt: 'Sqrt',
      log: 'Ln', exp: 'Exp', floor: 'Floor', ceil: 'Ceil', round: 'Round'
    }
  }),

  bash: toProfile('bash', 'Bash', {
    indent: '    ',
    comment: '# @text',
    header: '#!/usr/bin/env bash\n# Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)\nset -u',
    declare: '@name=@init',
    declareArray: 'declare -a @name  # size: @size\n@name=()',
    assign: '@name=@expr',
    input: 'read -r @name',
    output: 'echo @expr',
    outputNoNewline: 'echo -n @expr',
    ifOpen: 'if [ @cond ]; then',
    ifElse: 'else',
    ifClose: 'fi',
    whileOpen: 'while [ @cond ]; do',
    whileClose: 'done',
    forOpen: 'for (( @name = @start; @name <= @end; @name += @step )); do',
    forOpenDesc: 'for (( @name = @start; @name >= @end; @name -= @step )); do',
    forClose: 'done',
    doOpen: 'while true; do',
    doClose: 'if ! ( @cond ); then break; fi\ndone',
    call: '@name @args',
    types: { Integer: 'int', Real: 'float', String: 'string', Boolean: 'bool' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'false' },
    and: ' && ',
    or: ' || ',
    not: '! ',
    concat: ' + ',
    eq: '='
  }),

  caddis: toProfile('caddis', 'Caddis Pseudocode', {
    indent: '    ',
    comment: '// @text',
    header: '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: '@name = @init',
    declareArray: '@name[@size] = {}',
    assign: '@name = @expr',
    input: '@name = input',
    output: 'output @expr',
    outputNoNewline: 'output @expr',
    ifOpen: 'if @cond then',
    ifElse: 'else',
    ifClose: 'end if',
    whileOpen: 'while @cond',
    whileClose: 'end while',
    forOpen: 'loop @name from @start to @end',
    forOpenDesc: 'loop @name from @start down to @end',
    forClose: 'end loop',
    doOpen: 'loop',
    doClose: 'until @cond',
    call: '@name(@args)',
    types: { Integer: 'integer', Real: 'real', String: 'string', Boolean: 'boolean' },
    init: { Integer: '0', Real: '0.0', String: '""', Boolean: 'false' },
    and: ' and ',
    or: ' or ',
    not: 'not ',
    concat: ' + ',
    eq: '='
  }),

  ibo: toProfile('ibo', 'IBO Pseudocode', {
    indent: '    ',
    comment: '// @text',
    header: '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: '@name = @init',
    declareArray: '@name[@size] = {}',
    assign: '@name = @expr',
    input: '@name = input',
    output: 'output @expr',
    outputNoNewline: 'output @expr',
    ifOpen: 'if @cond then',
    ifElse: 'else',
    ifClose: 'end if',
    whileOpen: 'loop while @cond',
    whileClose: 'end loop',
    forOpen: 'loop @name from @start to @end',
    forOpenDesc: 'loop @name from @start down to @end',
    forClose: 'end loop',
    doOpen: 'loop',
    doClose: 'until @cond',
    call: '@name(@args)',
    types: { Integer: 'integer', Real: 'real', String: 'string', Boolean: 'boolean' },
    init: { Integer: '0', Real: '0.0', String: '""', Boolean: 'false' },
    and: ' and ',
    or: ' or ',
    not: 'not ',
    concat: ' + ',
    eq: '='
  }),

  autopseudo: toProfile('autopseudo', 'Auto Pseudocode', {
    indent: '   ',
    comment: '// @text',
    header: '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: 'Declare @name',
    declareArray: 'Declare @name[@size]',
    assign: '@name = @expr',
    input: 'Input @name',
    output: 'Output @expr',
    outputNoNewline: 'Output @expr',
    ifOpen: 'If @cond Then',
    ifElse: 'Else',
    ifClose: 'End If',
    whileOpen: 'While @cond',
    whileClose: 'End While',
    forOpen: 'For @name = @start to @end Step @step',
    forOpenDesc: 'For @name = @start to @end Step -@step',
    forClose: 'End For',
    doOpen: 'Do',
    doClose: 'While @cond',
    call: '@name(@args)',
    types: { Integer: 'Integer', Real: 'Real', String: 'String', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0.0', String: '""', Boolean: 'false' },
    and: ' And ',
    or: ' Or ',
    not: 'Not ',
    concat: ' & ',
    eq: '='
  }),

  fortran: toProfile('fortran', 'Fortran 2003', {
    indent: '  ',
    bodyIndent: '  ',
    comment: '! @text',
    header: [
      '! Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
      'program Main',
      '@declarations'
    ].join('\n'),
    footer: 'end program Main',
    hoistDeclarations: true,
    declare: '@type :: @name = @init',
    declareArray: '@type, dimension(@size) :: @name',
    assign: '@name = @expr',
    input: 'read *, @name',
    output: 'print *, @expr',
    outputNoNewline: "write(*, '(A)', advance='no') @expr",
    ifOpen: 'if (@cond) then',
    ifElse: 'else',
    ifClose: 'end if',
    whileOpen: 'do while (@cond)',
    whileClose: 'end do',
    forOpen: 'do @name = @start, @end, @step',
    forOpenDesc: 'do @name = @start, @end, -@step',
    forClose: 'end do',
    doOpen: 'do',
    doClose: 'if (.not. (@cond)) exit\nend do',
    call: 'call @name(@args)',
    types: { Integer: 'integer', Real: 'real', String: 'character(len=256)', Boolean: 'logical' },
    init: { Integer: '0', Real: '0.0', String: "''", Boolean: '.false.' },
    pi: '3.141592653589793',
    and: ' .and. ',
    or: ' .or. ',
    not: '.not. ',
    concat: ' // ',
    eq: '==',
    funcs: {
      abs: 'ABS', sin: 'SIN', cos: 'COS', tan: 'TAN', sqrt: 'SQRT',
      log: 'LOG', exp: 'EXP', floor: 'FLOOR', ceil: 'CEILING', round: 'NINT'
    }
  }),

  groovy: toProfile('groovy', 'Groovy', {
    header: '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: 'def @name = @init',
    declareArray: 'def @name = new Object[@size]',
    input: '@name = System.in.newReader().readLine()',
    output: 'println(@expr)',
    outputNoNewline: 'print(@expr)',
    types: { Integer: 'int', Real: 'double', String: 'String', Boolean: 'boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'false' },
    pi: 'Math.PI',
    mathPrefix: 'Math.'
  }),

  kotlin: toProfile('kotlin', 'Kotlin', {
    indent: '    ',
    comment: '// @text',
    header: [
      '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
      '',
      'fun main() {'
    ].join('\n'),
    footer: '}',
    bodyIndent: '    ',
    declare: 'var @name: @type = @init',
    declareArray: 'var @name = Array(@size) { @init }',
    assign: '@name = @expr',
    input: '@name = readLine()!!',
    inputTypes: {
      Integer: '@name = readLine()!!.toInt()',
      Real: '@name = readLine()!!.toDouble()',
      Boolean: '@name = readLine()!!.toBoolean()'
    },
    output: 'println(@expr)',
    outputNoNewline: 'print(@expr)',
    doOpen: 'do {',
    doClose: '} while (@cond)',
    types: { Integer: 'Int', Real: 'Double', String: 'String', Boolean: 'Boolean' },
    pi: 'Math.PI',
    mathPrefix: 'Math.'
  }),

  lua: toProfile('lua', 'Lua', {
    indent: '    ',
    comment: '-- @text',
    header: '-- Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: 'local @name = @init',
    declareArray: 'local @name = {}  -- size: @size',
    assign: '@name = @expr',
    input: '@name = io.read()',
    output: 'print(@expr)',
    outputNoNewline: 'io.write(@expr)',
    ifOpen: 'if @cond then',
    ifElse: 'else',
    ifClose: 'end',
    whileOpen: 'while @cond do',
    whileClose: 'end',
    forOpen: 'for @name = @start, @end, @step do',
    forOpenDesc: 'for @name = @start, @end, -@step do',
    forClose: 'end',
    doOpen: 'repeat',
    doClose: 'until @cond',
    call: '@name(@args)',
    types: { Integer: 'number', Real: 'number', String: 'string', Boolean: 'boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'false' },
    pi: 'math.pi',
    mathPrefix: 'math.',
    and: ' and ',
    or: ' or ',
    not: 'not ',
    concat: ' .. ',
    eq: '=='
  }),

  matlab: toProfile('matlab', 'MATLAB', {
    indent: '    ',
    comment: '% @text',
    quote: "'",
    header: '% Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: '@name = @init;',
    declareArray: '@name = zeros(1, @size);',
    assign: '@name = @expr;',
    input: "@name = input('');",
    output: 'disp(@expr);',
    outputNoNewline: "fprintf('%s', string(@expr));",
    ifOpen: 'if @cond',
    ifElse: 'else',
    ifClose: 'end',
    whileOpen: 'while @cond',
    whileClose: 'end',
    forOpen: 'for @name = @start:@step:@end',
    forOpenDesc: 'for @name = @start:-@step:@end',
    forClose: 'end',
    doOpen: 'while true',
    doClose: 'if ~(@cond)\n    break\nend\nend',
    call: '@name(@args);',
    types: { Integer: 'double', Real: 'double', String: 'char', Boolean: 'logical' },
    init: { Integer: '0', Real: '0', String: "''", Boolean: 'false' },
    pi: 'pi',
    eq: '=='
  }),

  netrexx: toProfile('netrexx', 'NetRexx', {
    indent: '    ',
    comment: '-- @text',
    header: '/* Generated by Flowonline2 (developed by PiBOH, AGPL-3.0) */',
    declare: '@name = @init',
    declareArray: '@name = @type[@size]',
    assign: '@name = @expr',
    input: '@name = Rexx(System.in.readLine())',
    output: 'say @expr',
    outputNoNewline: 'say @expr',
    ifOpen: 'if @cond then do',
    ifElse: 'end\nelse do',
    ifClose: 'end',
    whileOpen: 'loop while @cond',
    whileClose: 'end',
    forOpen: 'loop @name = @start to @end',
    forOpenDesc: 'loop @name = @start to @end by -1',
    forClose: 'end',
    doOpen: 'loop',
    doClose: 'if \\(@cond) then leave\nend',
    call: '@name(@args)',
    types: { Integer: 'int', Real: 'double', String: 'String', Boolean: 'boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'false' },
    and: ' & ',
    or: ' | ',
    not: '\\',
    concat: ' || ',
    eq: '='
  }),

  nim: toProfile('nim', 'Nim', {
    indent: '  ',
    comment: '# @text',
    emptyBody: 'discard',
    closeIndentAll: true,
    header: '# Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)\nimport std/[strutils, math]',
    declare: 'var @name: @type = @init',
    declareArray: 'var @name = newSeq[@type](@size)',
    assign: '@name = @expr',
    input: '@name = stdin.readLine()',
    output: 'echo @expr',
    outputNoNewline: 'stdout.write(@expr)',
    ifOpen: 'if @cond:',
    ifElse: 'else:',
    ifClose: '',
    whileOpen: 'while @cond:',
    whileClose: '',
    forOpen: 'for @name in @start .. @end:',
    forOpenDesc: 'for @name in countdown(@start, @end):',
    forClose: '',
    doOpen: 'while true:',
    doClose: 'if not (@cond):\n  break',
    call: '@name(@args)',
    types: { Integer: 'int', Real: 'float', String: 'string', Boolean: 'bool' },
    init: { Integer: '0', Real: '0.0', String: '""', Boolean: 'false' },
    pi: 'PI',
    mathPrefix: 'math.',
    and: ' and ',
    or: ' or ',
    not: 'not ',
    concat: ' & ',
    eq: '=='
  }),

  pascal: toProfile('pascal', 'Pascal', {
    indent: '  ',
    bodyIndent: '  ',
    comment: '// @text',
    quote: "'",
    header: ['{ Generated by Flowonline2 (developed by PiBOH, AGPL-3.0) }', 'program Main;', '@declarations', 'begin'].join('\n'),
    footer: 'end.',
    hoistDeclarations: true,
    hoistPreamble: 'var',
    declare: '@name : @type;',
    declareArray: '@name : array [1..@size] of @type;',
    assign: '@name := @expr;',
    input: 'readln(@name);',
    output: 'writeln(@expr);',
    outputNoNewline: 'write(@expr);',
    ifOpen: 'if @cond then\nbegin',
    ifElse: 'end\nelse\nbegin',
    ifClose: 'end;',
    whileOpen: 'while @cond do\nbegin',
    whileClose: 'end;',
    forOpen: 'for @name := @start to @end do\nbegin',
    forOpenDesc: 'for @name := @start downto @end do\nbegin',
    forClose: 'end;',
    doOpen: 'repeat',
    doClose: 'until @cond;',
    call: '@name(@args);',
    types: { Integer: 'Integer', Real: 'Real', String: 'string', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0.0', String: "''", Boolean: 'False' },
    pi: 'Pi',
    and: ' and ',
    or: ' or ',
    not: 'not ',
    concat: ' + ',
    eq: '=',
    funcs: {
      abs: 'Abs', sin: 'Sin', cos: 'Cos', tan: 'Tan', sqrt: 'Sqrt',
      log: 'Ln', exp: 'Exp', floor: 'Floor', ceil: 'Ceil', round: 'Round'
    }
  }),

  perl: toProfile('perl', 'Perl', {
    indent: '    ',
    comment: '# @text',
    header: '#!/usr/bin/perl\n# Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)\nuse strict;\nuse warnings;\nuse POSIX;',
    declare: 'my @name = @init;',
    declareArray: 'my @name = (undef) x @size;',
    assign: '@name = @expr;',
    input: 'chomp(@name = <STDIN>);',
    output: 'print @expr, "\\n";',
    outputNoNewline: 'print @expr;',
    ifOpen: 'if (@cond) {',
    ifElse: '} else {',
    ifClose: '}',
    whileOpen: 'while (@cond) {',
    whileClose: '}',
    forOpen: 'for (@name = @start; @name <= @end; @name += @step) {',
    forOpenDesc: 'for (@name = @start; @name >= @end; @name -= @step) {',
    doOpen: 'do {',
    doClose: '} while (@cond);',
    call: '@name(@args);',
    types: { Integer: 'scalar', Real: 'scalar', String: 'scalar', Boolean: 'scalar' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: '0' },
    varPrefix: '$',
    pi: '3.14159265358979',
    and: ' && ',
    or: ' || ',
    not: '!',
    concat: ' . ',
    eq: '==',
    funcs: { floor: 'int', ceil: 'POSIX::ceil', round: 'int' }
  }),

  php: toProfile('php', 'PHP', {
    indent: '    ',
    comment: '// @text',
    header: '<?php\n// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    footer: '?>',
    declare: '@name = @init;',
    declareArray: '@name = array_fill(0, @size, null);',
    assign: '@name = @expr;',
    input: '@name = trim(fgets(STDIN));',
    output: 'echo @expr, PHP_EOL;',
    outputNoNewline: 'echo @expr;',
    ifOpen: 'if (@cond) {',
    ifElse: '} else {',
    ifClose: '}',
    whileOpen: 'while (@cond) {',
    whileClose: '}',
    forOpen: 'for (@name = @start; @name <= @end; @name += @step) {',
    forOpenDesc: 'for (@name = @start; @name >= @end; @name -= @step) {',
    forClose: '}',
    doOpen: 'do {',
    doClose: '} while (@cond);',
    call: '@name(@args);',
    types: { Integer: 'int', Real: 'float', String: 'string', Boolean: 'bool' },
    init: { Integer: '0', Real: '0.0', String: '""', Boolean: 'false' },
    varPrefix: '$',
    pi: 'M_PI',
    inputTypes: {
      Integer: '$@name = (int) trim(fgets(STDIN));',
      Real: '$@name = (float) trim(fgets(STDIN));'
    },
    and: ' && ',
    or: ' || ',
    not: '!',
    concat: ' . ',
    eq: '=='
  }),

  powershell: toProfile('powershell', 'PowerShell', {
    indent: '    ',
    comment: '# @text',
    header: '# Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: '@name = @init',
    declareArray: '@name = New-Object object[] @size',
    assign: '@name = @expr',
    input: '@name = Read-Host "Enter a value"',
    output: 'Write-Host @expr',
    outputNoNewline: 'Write-Host @expr -NoNewline',
    ifOpen: 'if (@cond) {',
    ifElse: '} else {',
    ifClose: '}',
    whileOpen: 'while (@cond) {',
    whileClose: '}',
    forOpen: 'for (@name = @start; @name -le @end; @name += @step) {',
    forOpenDesc: 'for (@name = @start; @name -ge @end; @name -= @step) {',
    forClose: '}',
    doOpen: 'do {',
    doClose: '} while (@cond)',
    call: '@name @args',
    types: { Integer: 'int', Real: 'double', String: 'string', Boolean: 'bool' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: '$false' },
    varPrefix: '$',
    pi: '[Math]::PI',
    and: ' -and ',
    or: ' -or ',
    not: '-not ',
    concat: ' + ',
    eq: ' -eq ',
    funcs: {
      abs: '[Math]::Abs', sin: '[Math]::Sin', cos: '[Math]::Cos', tan: '[Math]::Tan',
      sqrt: '[Math]::Sqrt', log: '[Math]::Log', exp: '[Math]::Exp',
      floor: '[Math]::Floor', ceil: '[Math]::Ceiling', round: '[Math]::Round'
    }
  }),

  qbasic: toProfile('qbasic', 'QBasic', {
    indent: '    ',
    comment: "' @text",
    header: "' Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)",
    declare: 'DIM @name AS @type',
    declareArray: 'DIM @name(@size) AS @type',
    assign: '@name = @expr',
    input: 'INPUT @name',
    output: 'PRINT @expr',
    outputNoNewline: 'PRINT @expr;',
    ifOpen: 'IF @cond THEN',
    ifElse: 'ELSE',
    ifClose: 'END IF',
    whileOpen: 'WHILE @cond',
    whileClose: 'WEND',
    forOpen: 'FOR @name = @start TO @end STEP @step',
    forOpenDesc: 'FOR @name = @start TO @end STEP -@step',
    forClose: 'NEXT @name',
    doOpen: 'DO',
    doClose: 'LOOP WHILE @cond',
    call: '@name @args',
    types: { Integer: 'INTEGER', Real: 'SINGLE', String: 'STRING', Boolean: 'INTEGER' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: '0' },
    pi: '3.14159265358979',
    and: ' AND ',
    or: ' OR ',
    not: 'NOT ',
    concat: ' + ',
    eq: '=',
    funcs: { sqrt: 'SQR', floor: 'INT', ceil: 'INT', round: 'CINT' }
  }),

  ruby: toProfile('ruby', 'Ruby', {
    indent: '  ',
    comment: '# @text',
    header: '#!/usr/bin/env ruby\n# Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: '@name = @init',
    declareArray: '@name = Array.new(@size)',
    assign: '@name = @expr',
    input: '@name = gets.chomp',
    output: 'puts @expr',
    outputNoNewline: 'print @expr',
    ifOpen: 'if @cond',
    ifElse: 'else',
    ifClose: 'end',
    whileOpen: 'while @cond',
    whileClose: 'end',
    forOpen: 'for @name in @start..@end',
    forOpenDesc: 'for @name in @start.downto(@end)',
    forClose: 'end',
    doOpen: 'loop do',
    doClose: 'break unless @cond\nend',
    call: '@name(@args)',
    types: { Integer: 'Integer', Real: 'Float', String: 'String', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0.0', String: '""', Boolean: 'false' },
    pi: 'Math::PI',
    mathPrefix: 'Math.',
    and: ' && ',
    or: ' || ',
    not: '!',
    concat: ' + ',
    eq: '=='
  }),

  scala: toProfile('scala', 'Scala', {
    indent: '    ',
    comment: '// @text',
    header: [
      '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
      '',
      'object Main extends App {'
    ].join('\n'),
    footer: '}',
    bodyIndent: '    ',
    declare: 'var @name: @type = @init',
    declareArray: 'val @name = Array.ofDim[@type](@size)',
    assign: '@name = @expr',
    input: '@name = scala.io.StdIn.readLine()',
    inputTypes: {
      Integer: '@name = scala.io.StdIn.readInt()',
      Real: '@name = scala.io.StdIn.readDouble()',
      Boolean: '@name = scala.io.StdIn.readBoolean()'
    },
    output: 'println(@expr)',
    outputNoNewline: 'print(@expr)',
    forOpen: 'for (@name <- @start to @end by @step) {',
    forOpenDesc: 'for (@name <- @start to @end by -@step) {',
    doOpen: 'do {',
    doClose: '} while (@cond)',
    types: { Integer: 'Int', Real: 'Double', String: 'String', Boolean: 'Boolean' },
    pi: 'Math.PI',
    mathPrefix: 'Math.'
  }),

  smalltalk: toProfile('smalltalk', 'Smalltalk', {
    indent: '    ',
    comment: '"@text"',
    quote: "'",
    header: '"Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)"',
    declare: '@name := @init.',
    declareArray: '@name := Array new: @size.',
    assign: '@name := @expr.',
    input: "@name := FillInTheBlank request: 'Enter @name'.",
    output: 'Transcript show: @expr; cr.',
    outputNoNewline: 'Transcript show: @expr.',
    ifOpen: '(@cond) ifTrue: [',
    ifElse: '] ifFalse: [',
    ifClose: '].',
    whileOpen: '[@cond] whileTrue: [',
    whileClose: '].',
    forOpen: '@start to: @end do: [ :@name |',
    forOpenDesc: '@start to: @end by: -1 do: [ :@name |',
    forClose: '].',
    doOpen: '[',
    doClose: '] whileFalse: [@cond].',
    call: '@name value: @args',
    types: { Integer: 'Integer', Real: 'Float', String: 'String', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0', String: "''", Boolean: 'false' },
    pi: 'Float pi',
    and: ' & ',
    or: ' | ',
    not: 'not ',
    concat: ', ',
    eq: '='
  }),

  swift: toProfile('swift', 'Swift', {
    indent: '    ',
    comment: '// @text',
    header: '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)\nimport Foundation',
    declare: 'var @name: @type = @init',
    declareArray: 'var @name = [@type](repeating: @init, count: @size)',
    assign: '@name = @expr',
    input: '@name = readLine() ?? ""',
    inputTypes: {
      Integer: '@name = Int(readLine() ?? "") ?? 0',
      Real: '@name = Double(readLine() ?? "") ?? 0',
      Boolean: '@name = Bool(readLine() ?? "") ?? false'
    },
    output: 'print(@expr)',
    outputNoNewline: 'print(@expr, terminator: "")',
    forOpen: 'for @name in stride(from: @start, through: @end, by: @step) {',
    forOpenDesc: 'for @name in stride(from: @start, through: @end, by: -@step) {',
    doOpen: 'repeat {',
    doClose: '} while (@cond)',
    types: { Integer: 'Int', Real: 'Double', String: 'String', Boolean: 'Bool' },
    pi: 'Double.pi'
  }),

  tsql: toProfile('tsql', 'Transact-SQL', {
    indent: '    ',
    comment: '-- @text',
    quote: "'",
    header: '-- Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
    declare: 'DECLARE @name @type = @init;',
    declareArray: 'DECLARE @name TABLE (idx INT, val @type); -- size: @size',
    assign: 'SET @name = @expr;',
    input: 'SET @name = 0; -- input @name',
    output: 'PRINT @expr;',
    outputNoNewline: 'PRINT @expr;',
    ifOpen: 'IF (@cond)\nBEGIN',
    ifElse: 'END\nELSE\nBEGIN',
    ifClose: 'END',
    whileOpen: 'WHILE (@cond)\nBEGIN',
    whileClose: 'END',
    forOpen: 'DECLARE @name @type = @start;\nWHILE (@name <= @end)\nBEGIN',
    forOpenDesc: 'DECLARE @name @type = @start;\nWHILE (@name >= @end)\nBEGIN',
    forClose: 'SET @name = @name + @step;\nEND',
    doOpen: 'WHILE (1 = 1)\nBEGIN',
    doClose: 'IF NOT (@cond) BREAK;\nEND',
    call: 'EXEC @name @args;',
    types: { Integer: 'INT', Real: 'FLOAT', String: 'NVARCHAR(255)', Boolean: 'BIT' },
    init: { Integer: '0', Real: '0', String: "''", Boolean: '0' },
    varPrefix: '@',
    pi: 'PI()',
    and: ' AND ',
    or: ' OR ',
    not: 'NOT ',
    concat: ' + ',
    eq: '=',
    funcs: {
      abs: 'ABS', sin: 'SIN', cos: 'COS', tan: 'TAN', sqrt: 'SQRT',
      log: 'LOG', exp: 'EXP', floor: 'FLOOR', ceil: 'CEILING', round: 'ROUND'
    }
  }),

  typescript: toProfile('typescript', 'TypeScript', {
    indent: '    ',
    comment: '// @text',
    header: [
      '// Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)',
      '',
      'function main(): void {'
    ].join('\n'),
    footer: '}\n\nmain();',
    bodyIndent: '    ',
    declare: 'let @name: @type = @init;',
    declareArray: 'let @name: @type[] = new Array(@size).fill(@init);',
    input: '@name = prompt("Enter @name") ?? "";',
    inputTypes: {
      Integer: '@name = Number(prompt("Enter @name") ?? "0");',
      Real: '@name = Number(prompt("Enter @name") ?? "0");',
      Boolean: '@name = prompt("Enter @name") === "true";'
    },
    output: 'console.log(@expr);',
    outputNoNewline: 'process.stdout.write(String(@expr));',
    types: { Integer: 'number', Real: 'number', String: 'string', Boolean: 'boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'false' },
    pi: 'Math.PI',
    mathPrefix: 'Math.'
  }),

  vba: toProfile('vba', 'VBA', {
    indent: '    ',
    comment: "' @text",
    assign: '@name = @expr',
    header: ["' Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)", '', 'Sub Main()'].join('\n'),
    footer: 'End Sub',
    bodyIndent: '    ',
    declare: 'Dim @name As @type',
    declareArray: 'Dim @name(@size) As @type',
    input: '@name = InputBox("Enter @name")',
    output: 'Debug.Print @expr',
    outputNoNewline: 'Debug.Print @expr;',
    ifOpen: 'If @cond Then',
    ifElse: 'Else',
    ifClose: 'End If',
    whileOpen: 'Do While @cond',
    whileClose: 'Loop',
    forOpen: 'For @name = @start To @end Step @step',
    forOpenDesc: 'For @name = @start To @end Step -@step',
    forClose: 'Next @name',
    doOpen: 'Do',
    doClose: 'Loop While @cond',
    call: '@name @args',
    types: { Integer: 'Long', Real: 'Double', String: 'String', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'False' },
    pi: '4 * Atn(1)',
    and: ' And ',
    or: ' Or ',
    not: 'Not ',
    concat: ' & ',
    eq: '=',
    funcs: { sqrt: 'Sqr', floor: 'Int', ceil: 'Int', round: 'Round', abs: 'Abs' }
  }),

  vba_excel: toProfile('vba_excel', 'VBA (Excel)', {
    indent: '    ',
    comment: "' @text",
    assign: '@name = @expr',
    header: [
      "' Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)",
      "' Paste into a standard module of an Excel workbook.",
      '',
      'Sub Main()',
      '    Dim outputRow As Long',
      '    outputRow = 1'
    ].join('\n'),
    footer: 'End Sub',
    bodyIndent: '    ',
    declare: 'Dim @name As @type',
    declareArray: 'Dim @name(@size) As @type',
    input: '@name = InputBox("Enter @name")',
    output: 'Cells(outputRow, 1).Value = @expr\noutputRow = outputRow + 1',
    outputNoNewline: 'Debug.Print @expr;',
    ifOpen: 'If @cond Then',
    ifElse: 'Else',
    ifClose: 'End If',
    whileOpen: 'Do While @cond',
    whileClose: 'Loop',
    forOpen: 'For @name = @start To @end Step @step',
    forOpenDesc: 'For @name = @start To @end Step -@step',
    forClose: 'Next @name',
    doOpen: 'Do',
    doClose: 'Loop While @cond',
    call: '@name @args',
    types: { Integer: 'Long', Real: 'Double', String: 'String', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'False' },
    pi: '4 * Atn(1)',
    and: ' And ',
    or: ' Or ',
    not: 'Not ',
    concat: ' & ',
    eq: '=',
    funcs: { sqrt: 'Sqr', floor: 'Int', ceil: 'Int', round: 'Round', abs: 'Abs' }
  }),

  vbnet: toProfile('vbnet', 'Visual Basic .NET', {
    indent: '    ',
    comment: "' @text",
    assign: '@name = @expr',
    header: [
      "' Generated by Flowonline2 (developed by PiBOH, AGPL-3.0)",
      'Imports System',
      '',
      'Module Program',
      '    Sub Main(args As String())'
    ].join('\n'),
    footer: '    End Sub\nEnd Module',
    bodyIndent: '        ',
    declare: 'Dim @name As @type = @init',
    declareArray: 'Dim @name(@size) As @type',
    input: '@name = Console.ReadLine()',
    output: 'Console.WriteLine(@expr)',
    outputNoNewline: 'Console.Write(@expr)',
    ifOpen: 'If @cond Then',
    ifElse: 'Else',
    ifClose: 'End If',
    whileOpen: 'While @cond',
    whileClose: 'End While',
    forOpen: 'For @name = @start To @end Step @step',
    forOpenDesc: 'For @name = @start To @end Step -@step',
    forClose: 'Next @name',
    doOpen: 'Do',
    doClose: 'Loop While @cond',
    call: '@name(@args)',
    types: { Integer: 'Integer', Real: 'Double', String: 'String', Boolean: 'Boolean' },
    init: { Integer: '0', Real: '0', String: '""', Boolean: 'False' },
    pi: 'Math.PI',
    and: ' AndAlso ',
    or: ' OrElse ',
    not: 'Not ',
    concat: ' & ',
    eq: '=',
    funcs: {
      abs: 'Math.Abs', sin: 'Math.Sin', cos: 'Math.Cos', tan: 'Math.Tan',
      sqrt: 'Math.Sqrt', log: 'Math.Log', exp: 'Math.Exp',
      floor: 'Math.Floor', ceil: 'Math.Ceiling', round: 'Math.Round'
    }
  })
};

/** Every available source-code target, in Flowgorithm menu order. */
export const CODE_LANGUAGES: { id: string; label: string }[] = [
  { id: 'ada', label: 'Ada 95' },
  { id: 'applescript', label: 'AppleScript' },
  { id: 'autohotkey', label: 'AutoHotKey' },
  { id: 'bash', label: 'Bash' },
  { id: 'csharp', label: 'C#' },
  { id: 'cpp', label: 'C++' },
  { id: 'caddis', label: 'Caddis Pseudocode' },
  { id: 'fortran', label: 'Fortran 2003' },
  { id: 'groovy', label: 'Groovy' },
  { id: 'ibo', label: 'IBO Pseudocode' },
  { id: 'java', label: 'Java' },
  { id: 'javascript', label: 'JavaScript' },
  { id: 'kotlin', label: 'Kotlin' },
  { id: 'lua', label: 'Lua' },
  { id: 'matlab', label: 'MATLAB' },
  { id: 'netrexx', label: 'NetRexx' },
  { id: 'nim', label: 'Nim' },
  { id: 'pascal', label: 'Pascal' },
  { id: 'perl', label: 'Perl' },
  { id: 'php', label: 'PHP' },
  { id: 'powershell', label: 'Powershell' },
  { id: 'python', label: 'Python' },
  { id: 'qbasic', label: 'QBasic' },
  { id: 'ruby', label: 'Ruby' },
  { id: 'scala', label: 'Scala' },
  { id: 'smalltalk', label: 'Smalltalk' },
  { id: 'swift', label: 'Swift' },
  { id: 'tsql', label: 'Transact-SQL' },
  { id: 'typescript', label: 'TypeScript' },
  { id: 'vba', label: 'VBA' },
  { id: 'vba_excel', label: 'VBA (Excel)' },
  { id: 'vbnet', label: 'Visual Basic .NET' },
  { id: 'autopseudo', label: 'Auto Pseudocode' }
];
