import type { Language } from '../types/flow';

type TooltipKey = 'new' | 'open' | 'save' | 'copy' | 'favorite' | 'unfavorite' | 'searchExamples' | 'exportExamples' | 'format' | 'examplePath' | 'language';

const common: Record<TooltipKey, string> = {
  new: 'New (Ctrl+N)', open: 'Open (Ctrl+O)', save: 'Save (Ctrl+S)', copy: 'Copy', favorite: 'Add to favorites', unfavorite: 'Remove from favorites', searchExamples: 'Search examples by name, content, or author', exportExamples: 'Export examples list as JSON', format: 'File format', examplePath: 'Example file path', language: 'Select language'
};

const translations: Partial<Record<Language, Partial<Record<TooltipKey, string>>>> = {
  it: { new: 'Nuovo (Ctrl+N)', open: 'Apri (Ctrl+O)', save: 'Salva (Ctrl+S)', copy: 'Copia', favorite: 'Aggiungi ai preferiti', unfavorite: 'Rimuovi dai preferiti', searchExamples: 'Cerca esempi per nome, contenuto o autore', exportExamples: 'Esporta elenco esempi in JSON', format: 'Formato del file', examplePath: 'Percorso del file esempio', language: 'Seleziona lingua' },
  en_GB: { new: 'New (Ctrl+N)', open: 'Open (Ctrl+O)', save: 'Save (Ctrl+S)' },
  de: { new: 'Neu (Ctrl+N)', open: 'Öffnen (Ctrl+O)', save: 'Speichern (Ctrl+S)', copy: 'Kopieren', favorite: 'Zu Favoriten hinzufügen', unfavorite: 'Aus Favoriten entfernen', searchExamples: 'Beispiele nach Name, Inhalt oder Autor suchen', exportExamples: 'Beispielliste als JSON exportieren', format: 'Dateiformat', examplePath: 'Pfad der Beispieldatei', language: 'Sprache auswählen' },
  fr: { new: 'Nouveau (Ctrl+N)', open: 'Ouvrir (Ctrl+O)', save: 'Enregistrer (Ctrl+S)', copy: 'Copier', favorite: 'Ajouter aux favoris', unfavorite: 'Retirer des favoris', searchExamples: 'Rechercher des exemples par nom, contenu ou auteur', exportExamples: 'Exporter la liste des exemples en JSON', format: 'Format du fichier', examplePath: 'Chemin du fichier exemple', language: 'Choisir la langue' },
  es: { new: 'Nuevo (Ctrl+N)', open: 'Abrir (Ctrl+O)', save: 'Guardar (Ctrl+S)', copy: 'Copiar', favorite: 'Añadir a favoritos', unfavorite: 'Quitar de favoritos', searchExamples: 'Buscar ejemplos por nombre, contenido o autor', exportExamples: 'Exportar lista de ejemplos como JSON', format: 'Formato del archivo', examplePath: 'Ruta del archivo de ejemplo', language: 'Seleccionar idioma' },
  pt: { new: 'Novo (Ctrl+N)', open: 'Abrir (Ctrl+O)', save: 'Guardar (Ctrl+S)', copy: 'Copiar', favorite: 'Adicionar aos favoritos', unfavorite: 'Remover dos favoritos', searchExamples: 'Pesquisar exemplos por nome, conteúdo ou autor', exportExamples: 'Exportar lista de exemplos como JSON', format: 'Formato do ficheiro', examplePath: 'Caminho do ficheiro de exemplo', language: 'Selecionar idioma' },
  nl: { new: 'Nieuw (Ctrl+N)', open: 'Openen (Ctrl+O)', save: 'Opslaan (Ctrl+S)', copy: 'Kopiëren', favorite: 'Aan favorieten toevoegen', unfavorite: 'Uit favorieten verwijderen', searchExamples: 'Voorbeelden zoeken op naam, inhoud of auteur', exportExamples: 'Voorbeeldenlijst als JSON exporteren', format: 'Bestandsformaat', examplePath: 'Pad van voorbeeldbestand', language: 'Taal selecteren' },
  ru: { new: 'Новый (Ctrl+N)', open: 'Открыть (Ctrl+O)', save: 'Сохранить (Ctrl+S)', copy: 'Копировать', favorite: 'Добавить в избранное', unfavorite: 'Удалить из избранного', searchExamples: 'Поиск примеров по имени, содержимому или автору', exportExamples: 'Экспорт списка примеров в JSON', format: 'Формат файла', examplePath: 'Путь к файлу примера', language: 'Выбрать язык' },
  zh: { new: '新建 (Ctrl+N)', open: '打开 (Ctrl+O)', save: '保存 (Ctrl+S)', copy: '复制', favorite: '加入收藏', unfavorite: '移出收藏', searchExamples: '按名称、内容或作者搜索示例', exportExamples: '将示例列表导出为 JSON', format: '文件格式', examplePath: '示例文件路径', language: '选择语言' },
  ja: { new: '新規 (Ctrl+N)', open: '開く (Ctrl+O)', save: '保存 (Ctrl+S)', copy: 'コピー', favorite: 'お気に入りに追加', unfavorite: 'お気に入りから削除', searchExamples: '名前、内容、作者でサンプルを検索', exportExamples: 'サンプル一覧をJSONで書き出す', format: 'ファイル形式', examplePath: 'サンプルファイルのパス', language: '言語を選択' },
  uk: { new: 'Новий (Ctrl+N)', open: 'Відкрити (Ctrl+O)', save: 'Зберегти (Ctrl+S)', copy: 'Копіювати', favorite: 'Додати до обраного', unfavorite: 'Видалити з обраного', searchExamples: 'Пошук прикладів за назвою, вмістом або автором', exportExamples: 'Експорт списку прикладів у JSON', format: 'Формат файлу', examplePath: 'Шлях до файлу прикладу', language: 'Вибрати мову' },
  pl: { new: 'Nowy (Ctrl+N)', open: 'Otwórz (Ctrl+O)', save: 'Zapisz (Ctrl+S)', copy: 'Kopiuj', favorite: 'Dodaj do ulubionych', unfavorite: 'Usuń z ulubionych', searchExamples: 'Szukaj przykładów po nazwie, treści lub autorze', exportExamples: 'Eksportuj listę przykładów jako JSON', format: 'Format pliku', examplePath: 'Ścieżka pliku przykładu', language: 'Wybierz język' },
  cs: { new: 'Nový (Ctrl+N)', open: 'Otevřít (Ctrl+O)', save: 'Uložit (Ctrl+S)', copy: 'Kopírovat', favorite: 'Přidat do oblíbených', unfavorite: 'Odebrat z oblíbených', searchExamples: 'Hledat příklady podle názvu, obsahu nebo autora', exportExamples: 'Exportovat seznam příkladů jako JSON', format: 'Formát souboru', examplePath: 'Cesta k souboru příkladu', language: 'Vybrat jazyk' },
  hu: { new: 'Új (Ctrl+N)', open: 'Megnyitás (Ctrl+O)', save: 'Mentés (Ctrl+S)', copy: 'Másolás', favorite: 'Hozzáadás a kedvencekhez', unfavorite: 'Eltávolítás a kedvencekből', searchExamples: 'Példák keresése név, tartalom vagy szerző szerint', exportExamples: 'Példalisták exportálása JSON-ként', format: 'Fájlformátum', examplePath: 'Példafájl elérési útja', language: 'Nyelv kiválasztása' },
  sl: { new: 'Novo (Ctrl+N)', open: 'Odpri (Ctrl+O)', save: 'Shrani (Ctrl+S)', copy: 'Kopiraj', favorite: 'Dodaj med priljubljene', unfavorite: 'Odstrani iz priljubljenih', searchExamples: 'Išči primere po imenu, vsebini ali avtorju', exportExamples: 'Izvozi seznam primerov kot JSON', format: 'Oblika datoteke', examplePath: 'Pot do datoteke primera', language: 'Izberi jezik' },
  ar: { new: 'جديد (Ctrl+N)', open: 'فتح (Ctrl+O)', save: 'حفظ (Ctrl+S)', copy: 'نسخ', favorite: 'إضافة إلى المفضلة', unfavorite: 'إزالة من المفضلة', searchExamples: 'البحث عن الأمثلة بالاسم أو المحتوى أو المؤلف', exportExamples: 'تصدير قائمة الأمثلة بصيغة JSON', format: 'تنسيق الملف', examplePath: 'مسار ملف المثال', language: 'اختيار اللغة' },
  he: { new: 'חדש (Ctrl+N)', open: 'פתיחה (Ctrl+O)', save: 'שמירה (Ctrl+S)', copy: 'העתקה', favorite: 'הוספה למועדפים', unfavorite: 'הסרה מהמועדפים', searchExamples: 'חיפוש דוגמאות לפי שם, תוכן או מחבר', exportExamples: 'ייצוא רשימת הדוגמאות כ־JSON', format: 'תבנית הקובץ', examplePath: 'נתיב קובץ הדוגמה', language: 'בחירת שפה' },
  th: { new: 'ใหม่ (Ctrl+N)', open: 'เปิด (Ctrl+O)', save: 'บันทึก (Ctrl+S)', copy: 'คัดลอก', favorite: 'เพิ่มในรายการโปรด', unfavorite: 'ลบจากรายการโปรด', searchExamples: 'ค้นหาตัวอย่างตามชื่อ เนื้อหา หรือผู้เขียน', exportExamples: 'ส่งออกรายการตัวอย่างเป็น JSON', format: 'รูปแบบไฟล์', examplePath: 'เส้นทางไฟล์ตัวอย่าง', language: 'เลือกภาษา' },
  id: { new: 'Baru (Ctrl+N)', open: 'Buka (Ctrl+O)', save: 'Simpan (Ctrl+S)', copy: 'Salin', favorite: 'Tambah ke favorit', unfavorite: 'Hapus dari favorit', searchExamples: 'Cari contoh berdasarkan nama, isi, atau penulis', exportExamples: 'Ekspor daftar contoh sebagai JSON', format: 'Format berkas', examplePath: 'Lokasi berkas contoh', language: 'Pilih bahasa' },
  mn: { new: 'Шинэ (Ctrl+N)', open: 'Нээх (Ctrl+O)', save: 'Хадгалах (Ctrl+S)', copy: 'Хуулах', favorite: 'Дуртайд нэмэх', unfavorite: 'Дуртайгаас хасах', searchExamples: 'Нэр, агуулга эсвэл зохиогчоор жишээ хайх', exportExamples: 'Жишээний жагсаалтыг JSON болгон экспортлох', format: 'Файлын формат', examplePath: 'Жишээ файлын зам', language: 'Хэл сонгох' },
  fa: { new: 'جدید (Ctrl+N)', open: 'باز کردن (Ctrl+O)', save: 'ذخیره (Ctrl+S)', copy: 'کپی', favorite: 'افزودن به علاقه‌مندی‌ها', unfavorite: 'حذف از علاقه‌مندی‌ها', searchExamples: 'جستجوی نمونه‌ها بر اساس نام، محتوا یا نویسنده', exportExamples: 'خروجی فهرست نمونه‌ها به صورت JSON', format: 'قالب فایل', examplePath: 'مسیر فایل نمونه', language: 'انتخاب زبان' },
  gl: { new: 'Novo (Ctrl+N)', open: 'Abrir (Ctrl+O)', save: 'Gardar (Ctrl+S)', copy: 'Copiar', favorite: 'Engadir aos favoritos', unfavorite: 'Eliminar dos favoritos', searchExamples: 'Buscar exemplos por nome, contido ou autor', exportExamples: 'Exportar a lista de exemplos como JSON', format: 'Formato do ficheiro', examplePath: 'Ruta do ficheiro de exemplo', language: 'Seleccionar idioma' },
};

export const tooltip = (language: Language, key: TooltipKey): string => translations[language]?.[key] ?? common[key];
