import { Language, TranslationCatalog } from '../types/flow';

export const translations: Record<Language, TranslationCatalog> = {
  en: {
    title: "Flowonline2",
    subtitle: "Interactive Flowgorithm Clone",
    toolbar: { run: "Run", step: "Step", pause: "Pause", stop: "Stop", speed: "Speed", import: "Open .fprg", export: "Save .fprg", exportImage: "Export Image", exportJson: "Backup JSON", undo: "Undo", redo: "Redo", clear: "Clear All" },
    sidebar: { variables: "Variable Watch", codeGen: "Source Code", noVariables: "No variables declared yet.", varName: "Name", varType: "Type", varVal: "Value", watchTitle: "👁️ Variable Watch - Flowonline2", codeTitle: "📝 Source Code - Flowonline2", closeTooltip: "Close Panel", languageLabel: "Select Language", activeVariables: "Active Variables in Memory", valueLabel: "Value:" },
    blocks: { main: "Main", end: "End", declare: "Declare", assign: "Assign", input: "Input", output: "Output", if: "If", while: "While", for: "For", do: "Do", call: "Call", comment: "Comment" },
    modals: { title: "Edit Block", cancel: "Cancel", ok: "OK", declareVar: "Variable Name(s)", type: "Type", isArray: "Array?", arraySize: "Array Size / Dimension", assignTo: "Variable Name", expression: "Expression", inputVar: "Variable Name", outputExpr: "Expression (use & for concatenation)", newline: "New Line?", condition: "Condition (Boolean expression)", forVar: "Loop Variable", start: "Start Value", end: "End Value", step: "Step (increment)", direction: "Direction", ascending: "Increasing (Up)", descending: "Decreasing (Down)", callFunc: "Function Name", arguments: "Arguments (comma separated)", commentText: "Comment Text", errorTypeMismatch: "Value does not match the variable type.", errorRequired: "This field is required.", callFuncPlaceholder: "e.g. MyFunction", commentPlaceholder: "Write your annotations here...", blockCommentLabel: "Block Note/Comment (Optional)", blockCommentPlaceholder: "e.g. Check that age > 18", declarePlaceholder: "e.g. x, y, sum", assignPlaceholder: "e.g. sum, arr[i]", inputPlaceholder: "e.g. x, arr[idx]", outputPlaceholder: "e.g. \"Result: \" & sum" },
    errors: { executionError: "Execution Error", syntaxError: "Syntax Error in expression", varNotDefined: "Variable not defined", typeMismatch: "Type mismatch", arrayIndexOutOfBounds: "Array index out of bounds", divideByZero: "Division by zero" },
    console: { title: "💬 Execution Console - Flowonline2", clearBtn: "Clear", closeTooltip: "Close Panel", emptyMessage: "Console empty. Press \"Run\" to start the algorithm.", inputPlaceholder: "Type value and press Enter...", submitBtn: "Submit", readyStatus: "Ready", logCount: "Log: {0} lines" },
    canvas: { selectBlock: "Select Block" }
  },
  en_GB: {
    title: "Flowonline2",
    subtitle: "Interactive Flowgorithm Clone",
    toolbar: { run: "Run", step: "Step", pause: "Pause", stop: "Stop", speed: "Speed", import: "Open .fprg", export: "Save .fprg", exportImage: "Export Image", exportJson: "Backup JSON", undo: "Undo", redo: "Redo", clear: "Clear All" },
    sidebar: { variables: "Variable Watch", codeGen: "Source Code", noVariables: "No variables declared yet.", varName: "Name", varType: "Type", varVal: "Value", watchTitle: "👁️ Variable Watch - Flowonline2", codeTitle: "📝 Source Code - Flowonline2", closeTooltip: "Close Panel", languageLabel: "Select Language", activeVariables: "Active Variables in Memory", valueLabel: "Value:" },
    blocks: { main: "Main", end: "End", declare: "Declare", assign: "Assign", input: "Input", output: "Output", if: "If", while: "While", for: "For", do: "Do", call: "Call", comment: "Comment" },
    modals: { title: "Edit Block", cancel: "Cancel", ok: "OK", declareVar: "Variable Name(s)", type: "Type", isArray: "Array?", arraySize: "Array Size / Dimension", assignTo: "Variable Name", expression: "Expression", inputVar: "Variable Name", outputExpr: "Expression (use & for concatenation)", newline: "New Line?", condition: "Condition (Boolean expression)", forVar: "Loop Variable", start: "Start Value", end: "End Value", step: "Step (increment)", direction: "Direction", ascending: "Increasing (Up)", descending: "Decreasing (Down)", callFunc: "Function Name", arguments: "Arguments (comma separated)", commentText: "Comment Text", errorTypeMismatch: "Value does not match the variable type.", errorRequired: "This field is required.", callFuncPlaceholder: "e.g. MyFunction", commentPlaceholder: "Write your annotations here...", blockCommentLabel: "Block Note/Comment (Optional)", blockCommentPlaceholder: "e.g. Check that age > 18", declarePlaceholder: "e.g. x, y, sum", assignPlaceholder: "e.g. sum, arr[i]", inputPlaceholder: "e.g. x, arr[idx]", outputPlaceholder: "e.g. \"Result: \" & sum" },
    errors: { executionError: "Execution Error", syntaxError: "Syntax Error in expression", varNotDefined: "Variable not defined", typeMismatch: "Type mismatch", arrayIndexOutOfBounds: "Array index out of bounds", divideByZero: "Division by zero" },
    console: { title: "💬 Execution Console - Flowonline2", clearBtn: "Clear", closeTooltip: "Close Panel", emptyMessage: "Console empty. Press \"Run\" to start the algorithm.", inputPlaceholder: "Type value and press Enter...", submitBtn: "Submit", readyStatus: "Ready", logCount: "Log: {0} lines" },
    canvas: { selectBlock: "Select Block" }
  },
  it: {
    title: "Flowonline2", subtitle: "Replica Interattiva di Flowgorithm",
    toolbar: { run: "Esegui", step: "Passo-Passo", pause: "Pausa", stop: "Ferma", speed: "Velocità", import: "Apri .fprg", export: "Salva .fprg", exportImage: "Esporta Immagine", exportJson: "Backup JSON", undo: "Annulla", redo: "Rifai", clear: "Svuota Tutto" },
    sidebar: { variables: "Watch Variabili", codeGen: "Codice Sorgente", noVariables: "Nessuna variabile dichiarata.", varName: "Nome", varType: "Tipo", varVal: "Valore", watchTitle: "👁️ Watch Variabili - Flowonline2", codeTitle: "📝 Codice Sorgente - Flowonline2", closeTooltip: "Chiudi Pannello", languageLabel: "Seleziona Linguaggio", activeVariables: "Variabili Attive in Memoria", valueLabel: "Valore:" },
    blocks: { main: "Main", end: "End", declare: "Dichiara", assign: "Assegna", input: "Input", output: "Output", if: "Se (If)", while: "Mentre (While)", for: "Per (For)", do: "Esegui (Do)", call: "Chiamata", comment: "Commento" },
    modals: { title: "Modifica Blocco", cancel: "Annulla", ok: "OK", declareVar: "Nome Variabile/i", type: "Tipo", isArray: "Vettore (Array)?", arraySize: "Dimensione Vettore", assignTo: "Nome Variabile", expression: "Espressione", inputVar: "Nome Variabile", outputExpr: "Espressione (usa & per concatenare)", newline: "Nuova Linea?", condition: "Condizione (Espressione Booleana)", forVar: "Variabile Ciclo", start: "Valore Iniziale", end: "Valore Finale", step: "Passo (incremento)", direction: "Direzione", ascending: "Crescente (Su)", descending: "Decrescente (Giù)", callFunc: "Nome Funzione", arguments: "Argomenti (separati da virgola)", commentText: "Testo del Commento", errorTypeMismatch: "Il valore inserito non corrisponde al tipo di dato.", errorRequired: "Questo campo è obbligatorio.", callFuncPlaceholder: "es. MiaFunzione", commentPlaceholder: "Scrivi qui le annotazioni...", blockCommentLabel: "Nota/Commento del Blocco (Opzionale)", blockCommentPlaceholder: "es. Controlla che eta sia maggiore di 18", declarePlaceholder: "es. x, y, somma", assignPlaceholder: "es. somma, vettore[i]", inputPlaceholder: "es. x, vettore[idx]", outputPlaceholder: "es. \"Risultato: \" & somma" },
    errors: { executionError: "Errore di Esecuzione", syntaxError: "Errore di Sintassi nell'espressione", varNotDefined: "Variabile non definita", typeMismatch: "Incompatibilità di tipo", arrayIndexOutOfBounds: "Indice dell'array fuori dai limiti", divideByZero: "Divisione per zero" },
    console: { title: "💬 Console di Esecuzione - Flowonline2", clearBtn: "Svuota", closeTooltip: "Chiudi Pannello", emptyMessage: "Console vuota. Premi \"Esegui\" per avviare l'algoritmo.", inputPlaceholder: "Digita valore e premi Invio...", submitBtn: "Invia", readyStatus: "Pronto", logCount: "Log: {0} righe" },
    canvas: { selectBlock: "Seleziona Blocco" }
  },
  de: {
    title: "Flowonline2", subtitle: "Interaktiver Flowgorithm-Klon",
    toolbar: { run: "Ausführen", step: "Schritt", pause: "Pause", stop: "Stopp", speed: "Geschwindigkeit", import: ".fprg öffnen", export: ".fprg speichern", exportImage: "Bild exportieren", exportJson: "Backup-JSON", undo: "Rückgängig", redo: "Wiederholen", clear: "Alles löschen" },
    sidebar: { variables: "Variablen-Ansicht", codeGen: "Quellcode", noVariables: "Noch keine Variablen deklariert.", varName: "Name", varType: "Typ", varVal: "Wert", watchTitle: "👁️ Variablen-Ansicht - Flowonline2", codeTitle: "📝 Quellcode - Flowonline2", closeTooltip: "Panel schließen", languageLabel: "Sprache auswählen", activeVariables: "Aktive Variablen im Speicher", valueLabel: "Wert:" },
    blocks: { main: "Hauptprogramm", end: "Ende", declare: "Deklarieren", assign: "Zuweisen", input: "Eingabe", output: "Ausgabe", if: "Falls (If)", while: "Solange (While)", for: "Für (For)", do: "Ausführen (Do)", call: "Aufrufen", comment: "Kommentar" },
    modals: { title: "Block bearbeiten", cancel: "Abbrechen", ok: "OK", declareVar: "Variablenname(n)", type: "Typ", isArray: "Array?", arraySize: "Array-Größe / Dimension", assignTo: "Variablenname", expression: "Ausdruck", inputVar: "Variablenname", outputExpr: "Ausdruck (& für Verkettung)", newline: "Neue Zeile?", condition: "Bedingung (Boolescher Ausdruck)", forVar: "Laufvariable", start: "Startwert", end: "Endwert", step: "Schrittweite", direction: "Richtung", ascending: "Aufsteigend", descending: "Absteigend", callFunc: "Funktionsname", arguments: "Argumente (Komma-separiert)", commentText: "Kommentartext", errorTypeMismatch: "Wert entspricht nicht dem Variablentyp.", errorRequired: "Dieses Feld ist erforderlich.", callFuncPlaceholder: "z.B. MeineFunktion", commentPlaceholder: "Schreiben Sie hier Ihre Anmerkungen...", blockCommentLabel: "Block-Notiz/Kommentar (Optional)", blockCommentPlaceholder: "z.B. Prüfen, ob Alter > 18 ist", declarePlaceholder: "z.B. x, y, summe", assignPlaceholder: "z.B. summe, arr[i]", inputPlaceholder: "z.B. x, arr[idx]", outputPlaceholder: "z.B. \"Ergebnis: \" & summe" },
    errors: { executionError: "Ausführungsfehler", syntaxError: "Syntaxfehler im Ausdruck", varNotDefined: "Variable nicht definiert", typeMismatch: "Typkonflikt", arrayIndexOutOfBounds: "Array-Index außerhalb der Grenzen", divideByZero: "Division durch Null" },
    console: { title: "💬 Ausführungskonsole - Flowonline2", clearBtn: "Löschen", closeTooltip: "Panel schließen", emptyMessage: "Konsole leer. Drücken Sie \"Ausführen\" um den Algorithmus zu starten.", inputPlaceholder: "Wert eingeben und Enter drücken...", submitBtn: "Senden", readyStatus: "Bereit", logCount: "Log: {0} Zeilen" },
    canvas: { selectBlock: "Block auswählen" }
  },
  fr: {
    title: "Flowonline2", subtitle: "Clone Interactif de Flowgorithm",
    toolbar: { run: "Exécuter", step: "Pas à pas", pause: "Pause", stop: "Arrêter", speed: "Vitesse", import: "Ouvrir .fprg", export: "Enregistrer .fprg", exportImage: "Exporter Image", exportJson: "Sauvegarde JSON", undo: "Annuler", redo: "Rétablir", clear: "Tout effacer" },
    sidebar: { variables: "Variables", codeGen: "Code Source", noVariables: "Aucune variable déclarée.", varName: "Nom", varType: "Type", varVal: "Valeur", watchTitle: "👁️ Variables - Flowonline2", codeTitle: "📝 Code Source - Flowonline2", closeTooltip: "Fermer le panneau", languageLabel: "Sélectionner la langue", activeVariables: "Variables actives en mémoire", valueLabel: "Valeur :" },
    blocks: { main: "Principal (Main)", end: "Fin (End)", declare: "Déclarer", assign: "Affecter", input: "Lire (Input)", output: "Écrire (Output)", if: "Si (If)", while: "Tant que (While)", for: "Pour (For)", do: "Faire (Do)", call: "Appeler", comment: "Commentaire" },
    modals: { title: "Modifier le Bloc", cancel: "Annuler", ok: "OK", declareVar: "Nom de Variable", type: "Type", isArray: "Tableau?", arraySize: "Taille du tableau", assignTo: "Nom de Variable", expression: "Expression", inputVar: "Nom de Variable", outputExpr: "Expression (utilisez & pour concaténer)", newline: "Nouvelle ligne?", condition: "Condition (Expression booléenne)", forVar: "Variable de boucle", start: "Valeur de début", end: "Valeur de fin", step: "Pas (incrément)", direction: "Direction", ascending: "Croissant (Haut)", descending: "Décroissant (Bas)", callFunc: "Nom de la Fonction", arguments: "Arguments (séparés par des virgules)", commentText: "Texte du commentaire", errorTypeMismatch: "La valeur ne correspond pas au type de variable.", errorRequired: "Ce champ est requis.", callFuncPlaceholder: "ex. MaFonction", commentPlaceholder: "Écrivez vos annotations ici...", blockCommentLabel: "Note/Commentaire de bloc (Optionnel)", blockCommentPlaceholder: "ex. Vérifier que l'âge > 18", declarePlaceholder: "ex. x, y, somme", assignPlaceholder: "ex. somme, tab[i]", inputPlaceholder: "ex. x, tab[idx]", outputPlaceholder: "ex. \"Résultat : \" & somme" },
    errors: { executionError: "Erreur d'exécution", syntaxError: "Erreur de syntaxe", varNotDefined: "Variable non définie", typeMismatch: "Incompatibilité de type", arrayIndexOutOfBounds: "Index de tableau hors limites", divideByZero: "Division par zéro" },
    console: { title: "💬 Console d'exécution - Flowonline2", clearBtn: "Effacer", closeTooltip: "Fermer le panneau", emptyMessage: "Console vide. Appuyez sur \"Exécuter\" pour lancer l'algorithme.", inputPlaceholder: "Saisissez une valeur et appuyez sur Entrée...", submitBtn: "Envoyer", readyStatus: "Prêt", logCount: "Log : {0} lignes" },
    canvas: { selectBlock: "Sélectionner un bloc" }
  },
  es: {
    title: "Flowonline2", subtitle: "Clon Interactivo de Flowgorithm",
    toolbar: { run: "Ejecutar", step: "Paso a Paso", pause: "Pausa", stop: "Detener", speed: "Velocidad", import: "Abrir .fprg", export: "Guardar .fprg", exportImage: "Exportar Imagen", exportJson: "Copia JSON", undo: "Deshacer", redo: "Rehacer", clear: "Borrar Todo" },
    sidebar: { variables: "Variables", codeGen: "Código Fuente", noVariables: "No hay variables declaradas.", varName: "Nombre", varType: "Tipo", varVal: "Valor", watchTitle: "👁️ Variables - Flowonline2", codeTitle: "📝 Código Fuente - Flowonline2", closeTooltip: "Cerrar Panel", languageLabel: "Seleccionar Idioma", activeVariables: "Variables Activas en Memoria", valueLabel: "Valor:" },
    blocks: { main: "Principal (Main)", end: "Fin (End)", declare: "Declarar", assign: "Asignar", input: "Entrada (Input)", output: "Salida (Output)", if: "Si (If)", while: "Mientras (While)", for: "Para (For)", do: "Hacer (Do)", call: "Llamar", comment: "Comentario" },
    modals: { title: "Editar Bloque", cancel: "Cancelar", ok: "Aceptar", declareVar: "Nombre de Variable", type: "Tipo", isArray: "¿Es Matriz/Array?", arraySize: "Tamaño de la Matriz", assignTo: "Nombre de Variable", expression: "Expresión", inputVar: "Nombre de Variable", outputExpr: "Expresión (use & para concatenar)", newline: "¿Nueva Línea?", condition: "Condición (Expresión Booleana)", forVar: "Variable de Bucle", start: "Valor Inicial", end: "Valor Final", step: "Paso (incremento)", direction: "Dirección", ascending: "Ascendente (Incremento)", descending: "Descendente (Decremento)", callFunc: "Nombre de Función", arguments: "Argumentos (separados por comas)", commentText: "Texto del Comentario", errorTypeMismatch: "El valor no coincide con el tipo de variable.", errorRequired: "Este campo es requerido.", callFuncPlaceholder: "ej. MiFunción", commentPlaceholder: "Escriba sus anotaciones aquí...", blockCommentLabel: "Nota/Commentario del Bloque (Opcional)", blockCommentPlaceholder: "ej. Verificar que edad > 18", declarePlaceholder: "ej. x, y, suma", assignPlaceholder: "ej. suma, arr[i]", inputPlaceholder: "ej. x, arr[idx]", outputPlaceholder: "ej. \"Resultado: \" & suma" },
    errors: { executionError: "Error de Ejecución", syntaxError: "Error de Sintaxis", varNotDefined: "Variable no definida", typeMismatch: "Incompatibilidad de tipos", arrayIndexOutOfBounds: "Índice fuera de rango", divideByZero: "División por cero" },
    console: { title: "💬 Consola de Ejecución - Flowonline2", clearBtn: "Limpiar", closeTooltip: "Cerrar Panel", emptyMessage: "Consola vacía. Presione \"Ejecutar\" para iniciar el algoritmo.", inputPlaceholder: "Escriba un valor y presione Enter...", submitBtn: "Enviar", readyStatus: "Listo", logCount: "Log: {0} líneas" },
    canvas: { selectBlock: "Seleccionar Bloque" }
  },
  zh: {
    title: "Flowonline2", subtitle: "交互式 Flowgorithm 克隆",
    toolbar: { run: "运行", step: "单步", pause: "暂停", stop: "停止", speed: "速度", import: "打开 .fprg", export: "保存 .fprg", exportImage: "导出图像", exportJson: "备份 JSON", undo: "撤销", redo: "重做", clear: "全部清除" },
    sidebar: { variables: "变量监视", codeGen: "源代码", noVariables: "尚未声明变量。", varName: "名称", varType: "类型", varVal: "值", watchTitle: "👁️ 变量监视 - Flowonline2", codeTitle: "📝 源代码 - Flowonline2", closeTooltip: "关闭面板", languageLabel: "选择语言", activeVariables: "内存中的活动变量", valueLabel: "值:" },
    blocks: { main: "主程序", end: "结束", declare: "声明", assign: "赋值", input: "输入", output: "输出", if: "如果", while: "循环当", for: "循环从", do: "执行直到", call: "调用", comment: "注释" },
    modals: { title: "编辑块", cancel: "取消", ok: "确定", declareVar: "变量名", type: "类型", isArray: "数组?", arraySize: "数组大小/维度", assignTo: "变量名", expression: "表达式", inputVar: "变量名", outputExpr: "表达式 (使用 & 连接)", newline: "新行?", condition: "条件 (布尔表达式)", forVar: "循环变量", start: "起始值", end: "结束值", step: "步长", direction: "方向", ascending: "递增 (上)", descending: "递减 (下)", callFunc: "函数名", arguments: "参数 (逗号分隔)", commentText: "注释文本", errorTypeMismatch: "值与变量类型不匹配。", errorRequired: "此字段为必填。", callFuncPlaceholder: "例如: 我的函数", commentPlaceholder: "在此写下您的注释...", blockCommentLabel: "块注释 (可选)", blockCommentPlaceholder: "例如: 检查年龄 > 18", declarePlaceholder: "例如: x, y, sum", assignPlaceholder: "例如: sum, arr[i]", inputPlaceholder: "例如: x, arr[idx]", outputPlaceholder: "例如: \"结果: \" & sum" },
    errors: { executionError: "执行错误", syntaxError: "表达式语法错误", varNotDefined: "变量未定义", typeMismatch: "类型不匹配", arrayIndexOutOfBounds: "数组索引越界", divideByZero: "除以零" },
    console: { title: "💬 执行控制台 - Flowonline2", clearBtn: "清除", closeTooltip: "关闭面板", emptyMessage: "控制台为空。按\"运行\"启动算法。", inputPlaceholder: "输入值并按回车...", submitBtn: "提交", readyStatus: "就绪", logCount: "日志: {0} 行" },
    canvas: { selectBlock: "选择块" }
  },
  nl: {
    title: "Flowonline2", subtitle: "Interactieve Flowgorithm Kloon",
    toolbar: { run: "Uitvoeren", step: "Stap", pause: "Pauze", stop: "Stop", speed: "Snelheid", import: ".fprg openen", export: ".fprg opslaan", exportImage: "Afbeelding exporteren", exportJson: "Back-up JSON", undo: "Ongedaan", redo: "Opnieuw", clear: "Alles wissen" },
    sidebar: { variables: "Variabelen Bekijken", codeGen: "Broncode", noVariables: "Nog geen variabelen gedeclareerd.", varName: "Naam", varType: "Type", varVal: "Waarde", watchTitle: "👁️ Variabelen Bekijken - Flowonline2", codeTitle: "📝 Broncode - Flowonline2", closeTooltip: "Paneel sluiten", languageLabel: "Taal selecteren", activeVariables: "Actieve variabelen in geheugen", valueLabel: "Waarde:" },
    blocks: { main: "Hoofd", end: "Einde", declare: "Declareren", assign: "Toewijzen", input: "Invoer", output: "Uitvoer", if: "Als (If)", while: "Zolang (While)", for: "Voor (For)", do: "Doe (Do)", call: "Aanroepen", comment: "Commentaar" },
    modals: { title: "Blok Bewerken", cancel: "Annuleren", ok: "OK", declareVar: "Variabelenaam/namen", type: "Type", isArray: "Array?", arraySize: "Array-grootte / Dimensie", assignTo: "Variabelenaam", expression: "Expressie", inputVar: "Variabelenaam", outputExpr: "Expressie (gebruik & voor aaneenschakeling)", newline: "Nieuwe regel?", condition: "Voorwaarde (Booleaanse expressie)", forVar: "Lusvariabele", start: "Startwaarde", end: "Eindwaarde", step: "Stap (toename)", direction: "Richting", ascending: "Oplopend (Omhoog)", descending: "Aflopend (Omlaag)", callFunc: "Functienaam", arguments: "Argumenten (komma-gescheiden)", commentText: "Commentaartekst", errorTypeMismatch: "Waarde komt niet overeen met het variabeletype.", errorRequired: "Dit veld is verplicht.", callFuncPlaceholder: "bijv. MijnFunctie", commentPlaceholder: "Schrijf hier uw aantekeningen...", blockCommentLabel: "Bloknotitie/Commentaar (Optioneel)", blockCommentPlaceholder: "bijv. Controleer of leeftijd > 18", declarePlaceholder: "bijv. x, y, som", assignPlaceholder: "bijv. som, arr[i]", inputPlaceholder: "bijv. x, arr[idx]", outputPlaceholder: "bijv. \"Resultaat: \" & som" },
    errors: { executionError: "Uitvoeringsfout", syntaxError: "Syntaxisfout in expressie", varNotDefined: "Variabele niet gedefinieerd", typeMismatch: "Type komt niet overeen", arrayIndexOutOfBounds: "Array-index buiten bereik", divideByZero: "Deling door nul" },
    console: { title: "💬 Uitvoeringsconsole - Flowonline2", clearBtn: "Wissen", closeTooltip: "Paneel sluiten", emptyMessage: "Console leeg. Druk op \"Uitvoeren\" om het algoritme te starten.", inputPlaceholder: "Typ waarde en druk op Enter...", submitBtn: "Verzenden", readyStatus: "Gereed", logCount: "Log: {0} regels" },
    canvas: { selectBlock: "Blok selecteren" }
  },
  pt: {
    title: "Flowonline2", subtitle: "Clone Interativo do Flowgorithm",
    toolbar: { run: "Executar", step: "Passo a Passo", pause: "Pausa", stop: "Parar", speed: "Velocidade", import: "Abrir .fprg", export: "Salvar .fprg", exportImage: "Exportar Imagem", exportJson: "Backup JSON", undo: "Desfazer", redo: "Refazer", clear: "Limpar Tudo" },
    sidebar: { variables: "Variáveis", codeGen: "Código Fonte", noVariables: "Nenhuma variável declarada.", varName: "Nome", varType: "Tipo", varVal: "Valor", watchTitle: "👁️ Variáveis - Flowonline2", codeTitle: "📝 Código Fonte - Flowonline2", closeTooltip: "Fechar Painel", languageLabel: "Selecionar Idioma", activeVariables: "Variáveis Ativas na Memória", valueLabel: "Valor:" },
    blocks: { main: "Principal", end: "Fim", declare: "Declarar", assign: "Atribuir", input: "Entrada", output: "Saída", if: "Se (If)", while: "Enquanto (While)", for: "Para (For)", do: "Fazer (Do)", call: "Chamar", comment: "Comentário" },
    modals: { title: "Editar Bloco", cancel: "Cancelar", ok: "OK", declareVar: "Nome da(s) Variável(is)", type: "Tipo", isArray: "Matriz?", arraySize: "Tamanho da Matriz", assignTo: "Nome da Variável", expression: "Expressão", inputVar: "Nome da Variável", outputExpr: "Expressão (use & para concatenar)", newline: "Nova Linha?", condition: "Condição (Expressão Booleana)", forVar: "Variável do Laço", start: "Valor Inicial", end: "Valor Final", step: "Passo (incremento)", direction: "Direção", ascending: "Crescente (Sobe)", descending: "Decrescente (Desce)", callFunc: "Nome da Função", arguments: "Argumentos (separados por vírgula)", commentText: "Texto do Comentário", errorTypeMismatch: "Valor não corresponde ao tipo da variável.", errorRequired: "Este campo é obrigatório.", callFuncPlaceholder: "ex. MinhaFunção", commentPlaceholder: "Escreva suas anotações aqui...", blockCommentLabel: "Nota/Comentário do Bloco (Opcional)", blockCommentPlaceholder: "ex. Verificar se idade > 18", declarePlaceholder: "ex. x, y, soma", assignPlaceholder: "ex. soma, arr[i]", inputPlaceholder: "ex. x, arr[idx]", outputPlaceholder: "ex. \"Resultado: \" & soma" },
    errors: { executionError: "Erro de Execução", syntaxError: "Erro de Sintaxe na expressão", varNotDefined: "Variável não definida", typeMismatch: "Incompatibilidade de tipo", arrayIndexOutOfBounds: "Índice da matriz fora dos limites", divideByZero: "Divisão por zero" },
    console: { title: "💬 Console de Execução - Flowonline2", clearBtn: "Limpar", closeTooltip: "Fechar Painel", emptyMessage: "Console vazio. Pressione \"Executar\" para iniciar o algoritmo.", inputPlaceholder: "Digite o valor e pressione Enter...", submitBtn: "Enviar", readyStatus: "Pronto", logCount: "Log: {0} linhas" },
    canvas: { selectBlock: "Selecionar Bloco" }
  },
  gl: {
    title: "Flowonline2", subtitle: "Clon Interactivo de Flowgorithm",
    toolbar: { run: "Executar", step: "Paso a Paso", pause: "Pausa", stop: "Deter", speed: "Velocidade", import: "Abrir .fprg", export: "Gardar .fprg", exportImage: "Exportar Imaxe", exportJson: "Copia JSON", undo: "Desfacer", redo: "Refacer", clear: "Limpar Todo" },
    sidebar: { variables: "Variables", codeGen: "Código Fonte", noVariables: "Ningunha variable declarada.", varName: "Nome", varType: "Tipo", varVal: "Valor", watchTitle: "👁️ Variables - Flowonline2", codeTitle: "📝 Código Fonte - Flowonline2", closeTooltip: "Pechar Panel", languageLabel: "Seleccionar Idioma", activeVariables: "Variables Activas en Memoria", valueLabel: "Valor:" },
    blocks: { main: "Principal", end: "Fin", declare: "Declarar", assign: "Asignar", input: "Entrada", output: "Saída", if: "Se (If)", while: "Mentres (While)", for: "Para (For)", do: "Facer (Do)", call: "Chamar", comment: "Comentario" },
    modals: { title: "Editar Bloque", cancel: "Cancelar", ok: "OK", declareVar: "Nome da Variable", type: "Tipo", isArray: "Matriz?", arraySize: "Tamaño da Matriz", assignTo: "Nome da Variable", expression: "Expresión", inputVar: "Nome da Variable", outputExpr: "Expresión (use & para concatenar)", newline: "Nova Liña?", condition: "Condición (Expresión Booleana)", forVar: "Variable do Bucle", start: "Valor Inicial", end: "Valor Final", step: "Paso (incremento)", direction: "Dirección", ascending: "Crecente (Arriba)", descending: "Decrecente (Abaixo)", callFunc: "Nome da Función", arguments: "Argumentos (separados por comas)", commentText: "Texto do Comentario", errorTypeMismatch: "O valor non coincide co tipo da variable.", errorRequired: "Este campo é obrigatorio.", callFuncPlaceholder: "ex. MiñaFunción", commentPlaceholder: "Escriba aquí as súas anotacións...", blockCommentLabel: "Nota/Comentario do Bloque (Opcional)", blockCommentPlaceholder: "ex. Comprobar que idade > 18", declarePlaceholder: "ex. x, y, suma", assignPlaceholder: "ex. suma, arr[i]", inputPlaceholder: "ex. x, arr[idx]", outputPlaceholder: "ex. \"Resultado: \" & suma" },
    errors: { executionError: "Erro de Execución", syntaxError: "Erro de Sintaxe na expresión", varNotDefined: "Variable non definida", typeMismatch: "Incompatibilidade de tipo", arrayIndexOutOfBounds: "Índice da matriz fóra dos límites", divideByZero: "División por cero" },
    console: { title: "💬 Consola de Execución - Flowonline2", clearBtn: "Limpar", closeTooltip: "Pechar Panel", emptyMessage: "Consola baleira. Prema \"Executar\" para iniciar o algoritmo.", inputPlaceholder: "Escriba valor e prema Enter...", submitBtn: "Enviar", readyStatus: "Listo", logCount: "Log: {0} liñas" },
    canvas: { selectBlock: "Seleccionar Bloque" }
  },
  ru: {
    title: "Flowonline2", subtitle: "Интерактивный клон Flowgorithm",
    toolbar: { run: "Запуск", step: "Шаг", pause: "Пауза", stop: "Стоп", speed: "Скорость", import: "Открыть .fprg", export: "Сохранить .fprg", exportImage: "Экспорт изображения", exportJson: "Резервная JSON", undo: "Отменить", redo: "Повторить", clear: "Очистить всё" },
    sidebar: { variables: "Переменные", codeGen: "Исходный код", noVariables: "Переменные ещё не объявлены.", varName: "Имя", varType: "Тип", varVal: "Значение", watchTitle: "👁️ Переменные - Flowonline2", codeTitle: "📝 Исходный код - Flowonline2", closeTooltip: "Закрыть панель", languageLabel: "Выбрать язык", activeVariables: "Активные переменные в памяти", valueLabel: "Значение:" },
    blocks: { main: "Главная", end: "Конец", declare: "Объявить", assign: "Присвоить", input: "Ввод", output: "Вывод", if: "Если (If)", while: "Пока (While)", for: "Для (For)", do: "Делать (Do)", call: "Вызов", comment: "Комментарий" },
    modals: { title: "Редактировать блок", cancel: "Отмена", ok: "ОК", declareVar: "Имя переменной(ых)", type: "Тип", isArray: "Массив?", arraySize: "Размер массива", assignTo: "Имя переменной", expression: "Выражение", inputVar: "Имя переменной", outputExpr: "Выражение (используйте & для объединения)", newline: "Новая строка?", condition: "Условие (Булево выражение)", forVar: "Переменная цикла", start: "Начальное значение", end: "Конечное значение", step: "Шаг (приращение)", direction: "Направление", ascending: "По возрастанию (Вверх)", descending: "По убыванию (Вниз)", callFunc: "Имя функции", arguments: "Аргументы (через запятую)", commentText: "Текст комментария", errorTypeMismatch: "Значение не соответствует типу переменной.", errorRequired: "Это поле обязательно.", callFuncPlaceholder: "напр. МояФункция", commentPlaceholder: "Напишите здесь свои заметки...", blockCommentLabel: "Заметка/Комментарий блока (Необязательно)", blockCommentPlaceholder: "напр. Проверить, что возраст > 18", declarePlaceholder: "напр. x, y, сумма", assignPlaceholder: "напр. сумма, arr[i]", inputPlaceholder: "напр. x, arr[idx]", outputPlaceholder: "напр. \"Результат: \" & сумма" },
    errors: { executionError: "Ошибка выполнения", syntaxError: "Синтаксическая ошибка в выражении", varNotDefined: "Переменная не определена", typeMismatch: "Несоответствие типов", arrayIndexOutOfBounds: "Индекс массива вне диапазона", divideByZero: "Деление на ноль" },
    console: { title: "💬 Консоль выполнения - Flowonline2", clearBtn: "Очистить", closeTooltip: "Закрыть панель", emptyMessage: "Консоль пуста. Нажмите \"Запуск\" чтобы начать алгоритм.", inputPlaceholder: "Введите значение и нажмите Enter...", submitBtn: "Отправить", readyStatus: "Готов", logCount: "Лог: {0} строк" },
    canvas: { selectBlock: "Выбрать блок" }
  },
  uk: {
    title: "Flowonline2", subtitle: "Інтерактивний клон Flowgorithm",
    toolbar: { run: "Запуск", step: "Крок", pause: "Пауза", stop: "Стоп", speed: "Швидкість", import: "Відкрити .fprg", export: "Зберегти .fprg", exportImage: "Експорт зображення", exportJson: "Резервна JSON", undo: "Скасувати", redo: "Повторити", clear: "Очистити все" },
    sidebar: { variables: "Змінні", codeGen: "Вихідний код", noVariables: "Змінні ще не оголошені.", varName: "Ім'я", varType: "Тип", varVal: "Значення", watchTitle: "👁️ Змінні - Flowonline2", codeTitle: "📝 Вихідний код - Flowonline2", closeTooltip: "Закрити панель", languageLabel: "Вибрати мову", activeVariables: "Активні змінні в пам'яті", valueLabel: "Значення:" },
    blocks: { main: "Головна", end: "Кінець", declare: "Оголосити", assign: "Присвоїти", input: "Введення", output: "Виведення", if: "Якщо (If)", while: "Поки (While)", for: "Для (For)", do: "Робити (Do)", call: "Виклик", comment: "Коментар" },
    modals: { title: "Редагувати блок", cancel: "Скасувати", ok: "ОК", declareVar: "Ім'я змінної(их)", type: "Тип", isArray: "Масив?", arraySize: "Розмір масиву", assignTo: "Ім'я змінної", expression: "Вираз", inputVar: "Ім'я змінної", outputExpr: "Вираз (використовуйте & для об'єднання)", newline: "Новий рядок?", condition: "Умова (Булевий вираз)", forVar: "Змінна циклу", start: "Початкове значення", end: "Кінцеве значення", step: "Крок (приріст)", direction: "Напрямок", ascending: "За зростанням (Вгору)", descending: "За спаданням (Вниз)", callFunc: "Ім'я функції", arguments: "Аргументи (через кому)", commentText: "Текст коментаря", errorTypeMismatch: "Значення не відповідає типу змінної.", errorRequired: "Це поле обов'язкове.", callFuncPlaceholder: "напр. МояФункція", commentPlaceholder: "Напишіть тут свої нотатки...", blockCommentLabel: "Нотатка/Коментар блоку (Необов'язково)", blockCommentPlaceholder: "напр. Перевірити, що вік > 18", declarePlaceholder: "напр. x, y, сума", assignPlaceholder: "напр. сума, arr[i]", inputPlaceholder: "напр. x, arr[idx]", outputPlaceholder: "напр. \"Результат: \" & сума" },
    errors: { executionError: "Помилка виконання", syntaxError: "Синтаксична помилка у виразі", varNotDefined: "Змінна не визначена", typeMismatch: "Невідповідність типів", arrayIndexOutOfBounds: "Індекс масиву поза межами", divideByZero: "Ділення на нуль" },
    console: { title: "💬 Консоль виконання - Flowonline2", clearBtn: "Очистити", closeTooltip: "Закрити панель", emptyMessage: "Консоль порожня. Натисніть \"Запуск\" щоб почати алгоритм.", inputPlaceholder: "Введіть значення і натисніть Enter...", submitBtn: "Надіслати", readyStatus: "Готово", logCount: "Лог: {0} рядків" },
    canvas: { selectBlock: "Вибрати блок" }
  },
  cs: {
    title: "Flowonline2", subtitle: "Interaktivní klon Flowgorithm",
    toolbar: { run: "Spustit", step: "Krok", pause: "Pauza", stop: "Zastavit", speed: "Rychlost", import: "Otevřít .fprg", export: "Uložit .fprg", exportImage: "Exportovat obrázek", exportJson: "Záloha JSON", undo: "Zpět", redo: "Znovu", clear: "Vymazat vše" },
    sidebar: { variables: "Proměnné", codeGen: "Zdrojový kód", noVariables: "Zatím nejsou deklarovány žádné proměnné.", varName: "Název", varType: "Typ", varVal: "Hodnota", watchTitle: "👁️ Proměnné - Flowonline2", codeTitle: "📝 Zdrojový kód - Flowonline2", closeTooltip: "Zavřít panel", languageLabel: "Vybrat jazyk", activeVariables: "Aktivní proměnné v paměti", valueLabel: "Hodnota:" },
    blocks: { main: "Hlavní", end: "Konec", declare: "Deklarovat", assign: "Přiřadit", input: "Vstup", output: "Výstup", if: "Pokud (If)", while: "Dokud (While)", for: "Pro (For)", do: "Dělej (Do)", call: "Volání", comment: "Komentář" },
    modals: { title: "Upravit blok", cancel: "Zrušit", ok: "OK", declareVar: "Název proměnné(ných)", type: "Typ", isArray: "Pole?", arraySize: "Velikost pole / Dimenze", assignTo: "Název proměnné", expression: "Výraz", inputVar: "Název proměnné", outputExpr: "Výraz (použijte & pro spojení)", newline: "Nový řádek?", condition: "Podmínka (Booleovský výraz)", forVar: "Proměnná cyklu", start: "Počáteční hodnota", end: "Koncová hodnota", step: "Krok (přírůstek)", direction: "Směr", ascending: "Rostoucí (Nahoru)", descending: "Klesající (Dolů)", callFunc: "Název funkce", arguments: "Argumenty (oddělené čárkou)", commentText: "Text komentáře", errorTypeMismatch: "Hodnota neodpovídá typu proměnné.", errorRequired: "Toto pole je povinné.", callFuncPlaceholder: "např. MojeFunkce", commentPlaceholder: "Zde napište své poznámky...", blockCommentLabel: "Poznámka/Komentář bloku (Volitelné)", blockCommentPlaceholder: "např. Zkontrolujte, že věk > 18", declarePlaceholder: "např. x, y, součet", assignPlaceholder: "např. součet, arr[i]", inputPlaceholder: "např. x, arr[idx]", outputPlaceholder: "např. \"Výsledek: \" & součet" },
    errors: { executionError: "Chyba při provádění", syntaxError: "Syntaktická chyba ve výrazu", varNotDefined: "Proměnná není definována", typeMismatch: "Nesoulad typů", arrayIndexOutOfBounds: "Index pole mimo rozsah", divideByZero: "Dělení nulou" },
    console: { title: "💬 Prováděcí konzole - Flowonline2", clearBtn: "Vymazat", closeTooltip: "Zavřít panel", emptyMessage: "Konzole je prázdná. Stiskněte \"Spustit\" pro spuštění algoritmu.", inputPlaceholder: "Zadejte hodnotu a stiskněte Enter...", submitBtn: "Odeslat", readyStatus: "Připraven", logCount: "Log: {0} řádků" },
    canvas: { selectBlock: "Vybrat blok" }
  },
  pl: {
    title: "Flowonline2", subtitle: "Interaktywny klon Flowgorithm",
    toolbar: { run: "Uruchom", step: "Krok", pause: "Pauza", stop: "Zatrzymaj", speed: "Prędkość", import: "Otwórz .fprg", export: "Zapisz .fprg", exportImage: "Eksportuj obraz", exportJson: "Kopia JSON", undo: "Cofnij", redo: "Ponów", clear: "Wyczyść wszystko" },
    sidebar: { variables: "Zmienne", codeGen: "Kod źródłowy", noVariables: "Nie zadeklarowano jeszcze zmiennych.", varName: "Nazwa", varType: "Typ", varVal: "Wartość", watchTitle: "👁️ Zmienne - Flowonline2", codeTitle: "📝 Kod źródłowy - Flowonline2", closeTooltip: "Zamknij panel", languageLabel: "Wybierz język", activeVariables: "Aktywne zmienne w pamięci", valueLabel: "Wartość:" },
    blocks: { main: "Główny", end: "Koniec", declare: "Deklaruj", assign: "Przypisz", input: "Wejście", output: "Wyjście", if: "Jeśli (If)", while: "Dopóki (While)", for: "Dla (For)", do: "Wykonuj (Do)", call: "Wywołaj", comment: "Komentarz" },
    modals: { title: "Edytuj blok", cancel: "Anuluj", ok: "OK", declareVar: "Nazwa zmiennej(ych)", type: "Typ", isArray: "Tablica?", arraySize: "Rozmiar tablicy / Wymiar", assignTo: "Nazwa zmiennej", expression: "Wyrażenie", inputVar: "Nazwa zmiennej", outputExpr: "Wyrażenie (użyj & do łączenia)", newline: "Nowa linia?", condition: "Warunek (Wyrażenie logiczne)", forVar: "Zmienna pętli", start: "Wartość początkowa", end: "Wartość końcowa", step: "Krok (przyrost)", direction: "Kierunek", ascending: "Rosnący (W górę)", descending: "Malejący (W dół)", callFunc: "Nazwa funkcji", arguments: "Argumenty (oddzielone przecinkami)", commentText: "Tekst komentarza", errorTypeMismatch: "Wartość nie pasuje do typu zmiennej.", errorRequired: "To pole jest wymagane.", callFuncPlaceholder: "np. MojaFunkcja", commentPlaceholder: "Napisz tutaj swoje adnotacje...", blockCommentLabel: "Notatka/Komentarz bloku (Opcjonalnie)", blockCommentPlaceholder: "np. Sprawdź, czy wiek > 18", declarePlaceholder: "np. x, y, suma", assignPlaceholder: "np. suma, arr[i]", inputPlaceholder: "np. x, arr[idx]", outputPlaceholder: "np. \"Wynik: \" & suma" },
    errors: { executionError: "Błąd wykonania", syntaxError: "Błąd składni w wyrażeniu", varNotDefined: "Zmienna niezdefiniowana", typeMismatch: "Niezgodność typów", arrayIndexOutOfBounds: "Indeks tablicy poza zakresem", divideByZero: "Dzielenie przez zero" },
    console: { title: "💬 Konsola wykonania - Flowonline2", clearBtn: "Wyczyść", closeTooltip: "Zamknij panel", emptyMessage: "Konsola pusta. Naciśnij \"Uruchom\" aby rozpocząć algorytm.", inputPlaceholder: "Wpisz wartość i naciśnij Enter...", submitBtn: "Wyślij", readyStatus: "Gotowy", logCount: "Log: {0} linii" },
    canvas: { selectBlock: "Wybierz blok" }
  },
  hu: {
    title: "Flowonline2", subtitle: "Interaktív Flowgorithm Klón",
    toolbar: { run: "Futtatás", step: "Lépés", pause: "Szünet", stop: "Leállítás", speed: "Sebesség", import: ".fprg megnyitása", export: ".fprg mentése", exportImage: "Kép exportálása", exportJson: "Biztonsági JSON", undo: "Visszavonás", redo: "Mégis", clear: "Összes törlése" },
    sidebar: { variables: "Változók", codeGen: "Forráskód", noVariables: "Még nincsenek deklarált változók.", varName: "Név", varType: "Típus", varVal: "Érték", watchTitle: "👁️ Változók - Flowonline2", codeTitle: "📝 Forráskód - Flowonline2", closeTooltip: "Panel bezárása", languageLabel: "Nyelv kiválasztása", activeVariables: "Aktív változók a memóriában", valueLabel: "Érték:" },
    blocks: { main: "Főprogram", end: "Vége", declare: "Deklarálás", assign: "Értékadás", input: "Bemenet", output: "Kimenet", if: "Ha (If)", while: "Amíg (While)", for: "Ciklus (For)", do: "Végezd (Do)", call: "Hívás", comment: "Megjegyzés" },
    modals: { title: "Blokk szerkesztése", cancel: "Mégse", ok: "OK", declareVar: "Változó neve(k)", type: "Típus", isArray: "Tömb?", arraySize: "Tömb mérete / Dimenzió", assignTo: "Változó neve", expression: "Kifejezés", inputVar: "Változó neve", outputExpr: "Kifejezés (használjon &-et összefűzéshez)", newline: "Új sor?", condition: "Feltétel (Logikai kifejezés)", forVar: "Ciklusváltozó", start: "Kezdőérték", end: "Végérték", step: "Lépés (növekmény)", direction: "Irány", ascending: "Növekvő (Fel)", descending: "Csökkenő (Le)", callFunc: "Függvény neve", arguments: "Argumentumok (vesszővel elválasztva)", commentText: "Megjegyzés szövege", errorTypeMismatch: "Az érték nem egyezik a változó típusával.", errorRequired: "Ez a mező kötelező.", callFuncPlaceholder: "pl. SajátFüggvény", commentPlaceholder: "Ide írja megjegyzéseit...", blockCommentLabel: "Blokk megjegyzés (Opcionális)", blockCommentPlaceholder: "pl. Ellenőrizze, hogy életkor > 18", declarePlaceholder: "pl. x, y, összeg", assignPlaceholder: "pl. összeg, arr[i]", inputPlaceholder: "pl. x, arr[idx]", outputPlaceholder: "pl. \"Eredmény: \" & összeg" },
    errors: { executionError: "Végrehajtási hiba", syntaxError: "Szintaktikai hiba a kifejezésben", varNotDefined: "A változó nincs definiálva", typeMismatch: "Típuseltérés", arrayIndexOutOfBounds: "Tömb index túlcsordulás", divideByZero: "Nullával való osztás" },
    console: { title: "💬 Végrehajtási konzol - Flowonline2", clearBtn: "Törlés", closeTooltip: "Panel bezárása", emptyMessage: "A konzol üres. Nyomja meg a \"Futtatás\" gombot az algoritmus indításához.", inputPlaceholder: "Írja be az értéket és nyomjon Entert...", submitBtn: "Küldés", readyStatus: "Kész", logCount: "Napló: {0} sor" },
    canvas: { selectBlock: "Blokk kiválasztása" }
  },
  sl: {
    title: "Flowonline2", subtitle: "Interaktivni klon Flowgorithm",
    toolbar: { run: "Zaženi", step: "Korak", pause: "Premor", stop: "Ustavi", speed: "Hitrost", import: "Odpri .fprg", export: "Shrani .fprg", exportImage: "Izvozi sliko", exportJson: "Varnostna JSON", undo: "Razveljavi", redo: "Uveljavi", clear: "Počisti vse" },
    sidebar: { variables: "Spremenljivke", codeGen: "Izvorna koda", noVariables: "Nobena spremenljivka še ni deklarirana.", varName: "Ime", varType: "Tip", varVal: "Vrednost", watchTitle: "👁️ Spremenljivke - Flowonline2", codeTitle: "📝 Izvorna koda - Flowonline2", closeTooltip: "Zapri ploščo", languageLabel: "Izberi jezik", activeVariables: "Aktivne spremenljivke v pomnilniku", valueLabel: "Vrednost:" },
    blocks: { main: "Glavni", end: "Konec", declare: "Deklariraj", assign: "Priredi", input: "Vhod", output: "Izhod", if: "Če (If)", while: "Dokler (While)", for: "Za (For)", do: "Izvedi (Do)", call: "Klic", comment: "Komentar" },
    modals: { title: "Uredi blok", cancel: "Prekliči", ok: "V redu", declareVar: "Ime spremenljivke(k)", type: "Tip", isArray: "Tabela?", arraySize: "Velikost tabele / Dimenzija", assignTo: "Ime spremenljivke", expression: "Izraz", inputVar: "Ime spremenljivke", outputExpr: "Izraz (uporabite & za združevanje)", newline: "Nova vrstica?", condition: "Pogoj (Logični izraz)", forVar: "Spremenljivka zanke", start: "Začetna vrednost", end: "Končna vrednost", step: "Korak (prirastek)", direction: "Smer", ascending: "Naraščajoče (Gor)", descending: "Padajoče (Dol)", callFunc: "Ime funkcije", arguments: "Argumenti (ločeni z vejico)", commentText: "Besedilo komentarja", errorTypeMismatch: "Vrednost se ne ujema s tipom spremenljivke.", errorRequired: "To polje je obvezno.", callFuncPlaceholder: "npr. MojaFunkcija", commentPlaceholder: "Tukaj napišite svoje opombe...", blockCommentLabel: "Opomba/Komentar bloka (Neobvezno)", blockCommentPlaceholder: "npr. Preverite, da je starost > 18", declarePlaceholder: "npr. x, y, vsota", assignPlaceholder: "npr. vsota, arr[i]", inputPlaceholder: "npr. x, arr[idx]", outputPlaceholder: "npr. \"Rezultat: \" & vsota" },
    errors: { executionError: "Napaka pri izvajanju", syntaxError: "Skladenjska napaka v izrazu", varNotDefined: "Spremenljivka ni definirana", typeMismatch: "Neujemanje tipov", arrayIndexOutOfBounds: "Indeks tabele izven meja", divideByZero: "Deljenje z nič" },
    console: { title: "💬 Izvajalna konzola - Flowonline2", clearBtn: "Počisti", closeTooltip: "Zapri ploščo", emptyMessage: "Konzola je prazna. Pritisnite \"Zaženi\" za zagon algoritma.", inputPlaceholder: "Vnesite vrednost in pritisnite Enter...", submitBtn: "Pošlji", readyStatus: "Pripravljen", logCount: "Dnevnik: {0} vrstic" },
    canvas: { selectBlock: "Izberi blok" }
  },
  ja: {
    title: "Flowonline2", subtitle: "インタラクティブ Flowgorithm クローン",
    toolbar: { run: "実行", step: "ステップ", pause: "一時停止", stop: "停止", speed: "速度", import: ".fprg を開く", export: ".fprg を保存", exportImage: "画像をエクスポート", exportJson: "JSON バックアップ", undo: "元に戻す", redo: "やり直し", clear: "すべてクリア" },
    sidebar: { variables: "変数ウォッチ", codeGen: "ソースコード", noVariables: "まだ変数が宣言されていません。", varName: "名前", varType: "型", varVal: "値", watchTitle: "👁️ 変数ウォッチ - Flowonline2", codeTitle: "📝 ソースコード - Flowonline2", closeTooltip: "パネルを閉じる", languageLabel: "言語を選択", activeVariables: "メモリ内のアクティブ変数", valueLabel: "値:" },
    blocks: { main: "メイン", end: "終了", declare: "宣言", assign: "代入", input: "入力", output: "出力", if: "もし (If)", while: "の間 (While)", for: "のために (For)", do: "実行 (Do)", call: "呼び出し", comment: "コメント" },
    modals: { title: "ブロックを編集", cancel: "キャンセル", ok: "OK", declareVar: "変数名", type: "型", isArray: "配列?", arraySize: "配列サイズ/次元", assignTo: "変数名", expression: "式", inputVar: "変数名", outputExpr: "式 (連結には & を使用)", newline: "改行?", condition: "条件 (ブール式)", forVar: "ループ変数", start: "開始値", end: "終了値", step: "ステップ (増分)", direction: "方向", ascending: "増加 (上)", descending: "減少 (下)", callFunc: "関数名", arguments: "引数 (カンマ区切り)", commentText: "コメントテキスト", errorTypeMismatch: "値が変数型と一致しません。", errorRequired: "このフィールドは必須です。", callFuncPlaceholder: "例: MyFunction", commentPlaceholder: "ここに注釈を書いてください...", blockCommentLabel: "ブロックノート/コメント (オプション)", blockCommentPlaceholder: "例: 年齢 > 18 をチェック", declarePlaceholder: "例: x, y, sum", assignPlaceholder: "例: sum, arr[i]", inputPlaceholder: "例: x, arr[idx]", outputPlaceholder: "例: \"結果: \" & sum" },
    errors: { executionError: "実行エラー", syntaxError: "式の構文エラー", varNotDefined: "変数が定義されていません", typeMismatch: "型の不一致", arrayIndexOutOfBounds: "配列インデックスが範囲外です", divideByZero: "ゼロ除算" },
    console: { title: "💬 実行コンソール - Flowonline2", clearBtn: "クリア", closeTooltip: "パネルを閉じる", emptyMessage: "コンソールは空です。\"実行\" を押してアルゴリズムを開始してください。", inputPlaceholder: "値を入力して Enter を押してください...", submitBtn: "送信", readyStatus: "準備完了", logCount: "ログ: {0} 行" },
    canvas: { selectBlock: "ブロックを選択" }
  },
  th: {
    title: "Flowonline2", subtitle: "โคลน Flowgorithm แบบโต้ตอบ",
    toolbar: { run: "เริ่ม", step: "ทีละขั้น", pause: "หยุดชั่วคราว", stop: "หยุด", speed: "ความเร็ว", import: "เปิด .fprg", export: "บันทึก .fprg", exportImage: "ส่งออกรูปภาพ", exportJson: "สำรอง JSON", undo: "เลิกทำ", redo: "ทำซ้ำ", clear: "ล้างทั้งหมด" },
    sidebar: { variables: "ดูตัวแปร", codeGen: "ซอร์สโค้ด", noVariables: "ยังไม่ได้ประกาศตัวแปร", varName: "ชื่อ", varType: "ชนิด", varVal: "ค่า", watchTitle: "👁️ ดูตัวแปร - Flowonline2", codeTitle: "📝 ซอร์สโค้ด - Flowonline2", closeTooltip: "ปิดแผง", languageLabel: "เลือกภาษา", activeVariables: "ตัวแปรที่ใช้งานในหน่วยความจำ", valueLabel: "ค่า:" },
    blocks: { main: "หลัก", end: "จบ", declare: "ประกาศ", assign: "กำหนดค่า", input: "รับค่า", output: "แสดงผล", if: "ถ้า (If)", while: "ขณะที่ (While)", for: "สำหรับ (For)", do: "ทำ (Do)", call: "เรียกใช้", comment: "หมายเหตุ" },
    modals: { title: "แก้ไขบล็อก", cancel: "ยกเลิก", ok: "ตกลง", declareVar: "ชื่อตัวแปร", type: "ชนิด", isArray: "อาร์เรย์?", arraySize: "ขนาดอาร์เรย์/มิติ", assignTo: "ชื่อตัวแปร", expression: "นิพจน์", inputVar: "ชื่อตัวแปร", outputExpr: "นิพจน์ (ใช้ & เพื่อต่อข้อความ)", newline: "ขึ้นบรรทัดใหม่?", condition: "เงื่อนไข (นิพจน์บูลีน)", forVar: "ตัวแปรลูป", start: "ค่าเริ่มต้น", end: "ค่าสิ้นสุด", step: "ขั้น (เพิ่มขึ้น)", direction: "ทิศทาง", ascending: "เพิ่มขึ้น (ขึ้น)", descending: "ลดลง (ลง)", callFunc: "ชื่อฟังก์ชัน", arguments: "อาร์กิวเมนต์ (คั่นด้วยจุลภาค)", commentText: "ข้อความหมายเหตุ", errorTypeMismatch: "ค่าไม่ตรงกับชนิดตัวแปร", errorRequired: "ฟิลด์นี้จำเป็น", callFuncPlaceholder: "เช่น MyFunction", commentPlaceholder: "เขียนคำอธิบายที่นี่...", blockCommentLabel: "บันทึก/หมายเหตุบล็อก (ไม่บังคับ)", blockCommentPlaceholder: "เช่น ตรวจสอบว่าอายุ > 18", declarePlaceholder: "เช่น x, y, sum", assignPlaceholder: "เช่น sum, arr[i]", inputPlaceholder: "เช่น x, arr[idx]", outputPlaceholder: "เช่น \"ผลลัพธ์: \" & sum" },
    errors: { executionError: "ข้อผิดพลาดในการดำเนินการ", syntaxError: "ข้อผิดพลาดทางไวยากรณ์ในนิพจน์", varNotDefined: "ไม่ได้กำหนดตัวแปร", typeMismatch: "ชนิดไม่ตรงกัน", arrayIndexOutOfBounds: "ดัชนีอาร์เรย์เกินขอบเขต", divideByZero: "หารด้วยศูนย์" },
    console: { title: "💬 คอนโซลการดำเนินการ - Flowonline2", clearBtn: "ล้าง", closeTooltip: "ปิดแผง", emptyMessage: "คอนโซลว่างเปล่า กด \"เริ่ม\" เพื่อเริ่มอัลกอริทึม", inputPlaceholder: "พิมพ์ค่าแล้วกด Enter...", submitBtn: "ส่ง", readyStatus: "พร้อม", logCount: "บันทึก: {0} บรรทัด" },
    canvas: { selectBlock: "เลือกบล็อก" }
  },
  id: {
    title: "Flowonline2", subtitle: "Klon Flowgorithm Interaktif",
    toolbar: { run: "Jalankan", step: "Langkah", pause: "Jeda", stop: "Berhenti", speed: "Kecepatan", import: "Buka .fprg", export: "Simpan .fprg", exportImage: "Ekspor Gambar", exportJson: "Cadangan JSON", undo: "Urungkan", redo: "Ulangi", clear: "Bersihkan Semua" },
    sidebar: { variables: "Pantau Variabel", codeGen: "Kode Sumber", noVariables: "Belum ada variabel yang dideklarasikan.", varName: "Nama", varType: "Tipe", varVal: "Nilai", watchTitle: "👁️ Pantau Variabel - Flowonline2", codeTitle: "📝 Kode Sumber - Flowonline2", closeTooltip: "Tutup Panel", languageLabel: "Pilih Bahasa", activeVariables: "Variabel Aktif di Memori", valueLabel: "Nilai:" },
    blocks: { main: "Utama", end: "Selesai", declare: "Deklarasi", assign: "Tetapkan", input: "Masukan", output: "Keluaran", if: "Jika (If)", while: "Selama (While)", for: "Untuk (For)", do: "Lakukan (Do)", call: "Panggil", comment: "Komentar" },
    modals: { title: "Edit Blok", cancel: "Batal", ok: "OK", declareVar: "Nama Variabel", type: "Tipe", isArray: "Array?", arraySize: "Ukuran Array / Dimensi", assignTo: "Nama Variabel", expression: "Ekspresi", inputVar: "Nama Variabel", outputExpr: "Ekspresi (gunakan & untuk penggabungan)", newline: "Baris Baru?", condition: "Kondisi (Ekspresi Boolean)", forVar: "Variabel Loop", start: "Nilai Awal", end: "Nilai Akhir", step: "Langkah (kenaikan)", direction: "Arah", ascending: "Menaik (Atas)", descending: "Menurun (Bawah)", callFunc: "Nama Fungsi", arguments: "Argumen (dipisahkan koma)", commentText: "Teks Komentar", errorTypeMismatch: "Nilai tidak cocok dengan tipe variabel.", errorRequired: "Bidang ini wajib diisi.", callFuncPlaceholder: "mis. FungsiSaya", commentPlaceholder: "Tulis anotasi Anda di sini...", blockCommentLabel: "Catatan/Komentar Blok (Opsional)", blockCommentPlaceholder: "mis. Periksa bahwa usia > 18", declarePlaceholder: "mis. x, y, jumlah", assignPlaceholder: "mis. jumlah, arr[i]", inputPlaceholder: "mis. x, arr[idx]", outputPlaceholder: "mis. \"Hasil: \" & jumlah" },
    errors: { executionError: "Kesalahan Eksekusi", syntaxError: "Kesalahan Sintaks dalam ekspresi", varNotDefined: "Variabel tidak didefinisikan", typeMismatch: "Ketidakcocokan tipe", arrayIndexOutOfBounds: "Indeks array di luar batas", divideByZero: "Pembagian dengan nol" },
    console: { title: "💬 Konsol Eksekusi - Flowonline2", clearBtn: "Bersihkan", closeTooltip: "Tutup Panel", emptyMessage: "Konsol kosong. Tekan \"Jalankan\" untuk memulai algoritma.", inputPlaceholder: "Ketik nilai dan tekan Enter...", submitBtn: "Kirim", readyStatus: "Siap", logCount: "Log: {0} baris" },
    canvas: { selectBlock: "Pilih Blok" }
  },
  mn: {
    title: "Flowonline2", subtitle: "Интерактив Flowgorithm клон",
    toolbar: { run: "Ажиллуулах", step: "Алхам", pause: "Түр зогсоох", stop: "Зогсоох", speed: "Хурд", import: ".fprg нээх", export: ".fprg хадгалах", exportImage: "Зураг экспортлох", exportJson: "JSON нөөцлөх", undo: "Буцаах", redo: "Давтах", clear: "Бүгдийг цэвэрлэх" },
    sidebar: { variables: "Хувьсагчид", codeGen: "Эх код", noVariables: "Одоогоор хувьсагч зарлаагүй байна.", varName: "Нэр", varType: "Төрөл", varVal: "Утга", watchTitle: "👁️ Хувьсагчид - Flowonline2", codeTitle: "📝 Эх код - Flowonline2", closeTooltip: "Самбарыг хаах", languageLabel: "Хэл сонгох", activeVariables: "Санах ой дахь идэвхтэй хувьсагчид", valueLabel: "Утга:" },
    blocks: { main: "Үндсэн", end: "Төгсгөл", declare: "Зарлах", assign: "Оноох", input: "Оролт", output: "Гаралт", if: "Хэрэв (If)", while: "Бол (While)", for: "Төлөө (For)", do: "Хий (Do)", call: "Дуудах", comment: "Тайлбар" },
    modals: { title: "Блок засварлах", cancel: "Цуцлах", ok: "OK", declareVar: "Хувьсагчийн нэр(нүүд)", type: "Төрөл", isArray: "Массив?", arraySize: "Массивын хэмжээ", assignTo: "Хувьсагчийн нэр", expression: "Илэрхийлэл", inputVar: "Хувьсагчийн нэр", outputExpr: "Илэрхийлэл (холбоход & ашиглах)", newline: "Шинэ мөр?", condition: "Нөхцөл (Булийн илэрхийлэл)", forVar: "Давталтын хувьсагч", start: "Эхлэх утга", end: "Төгсгөх утга", step: "Алхам (өсөлт)", direction: "Чиглэл", ascending: "Өсөх (Дээш)", descending: "Буурах (Доош)", callFunc: "Функцийн нэр", arguments: "Аргументууд (таслалаар тусгаарлах)", commentText: "Тайлбар текст", errorTypeMismatch: "Утга нь хувьсагчийн төрөлтэй тохирохгүй байна.", errorRequired: "Энэ талбар шаардлагатай.", callFuncPlaceholder: "жнь. МинийФункц", commentPlaceholder: "Тэмдэглэлээ энд бичнэ үү...", blockCommentLabel: "Блок тэмдэглэл/Тайлбар (Сонголттой)", blockCommentPlaceholder: "жнь. Нас > 18 эсэхийг шалгах", declarePlaceholder: "жнь. x, y, нийлбэр", assignPlaceholder: "жнь. нийлбэр, arr[i]", inputPlaceholder: "жнь. x, arr[idx]", outputPlaceholder: "жнь. \"Үр дүн: \" & нийлбэр" },
    errors: { executionError: "Гүйцэтгэлийн алдаа", syntaxError: "Илэрхийлэл дэх синтакс алдаа", varNotDefined: "Хувьсагч тодорхойлогдоогүй", typeMismatch: "Төрөл тохирохгүй", arrayIndexOutOfBounds: "Массивын индекс хязгаараас хэтэрсэн", divideByZero: "Тэгээр хуваах" },
    console: { title: "💬 Гүйцэтгэлийн консол - Flowonline2", clearBtn: "Цэвэрлэх", closeTooltip: "Самбарыг хаах", emptyMessage: "Консол хоосон. Алгоритмыг эхлүүлэхийн тулд \"Ажиллуулах\" дээр дарна уу.", inputPlaceholder: "Утга оруулаад Enter дарна уу...", submitBtn: "Илгээх", readyStatus: "Бэлэн", logCount: "Лог: {0} мөр" },
    canvas: { selectBlock: "Блок сонгох" }
  },
  ar: {
    title: "Flowonline2", subtitle: "نسخة تفاعلية من Flowgorithm",
    toolbar: { run: "تشغيل", step: "خطوة", pause: "إيقاف مؤقت", stop: "إيقاف", speed: "السرعة", import: "فتح .fprg", export: "حفظ .fprg", exportImage: "تصدير صورة", exportJson: "نسخ JSON احتياطي", undo: "تراجع", redo: "إعادة", clear: "مسح الكل" },
    sidebar: { variables: "مراقبة المتغيرات", codeGen: "الكود المصدري", noVariables: "لم يتم تعريف متغيرات بعد.", varName: "الاسم", varType: "النوع", varVal: "القيمة", watchTitle: "👁️ مراقبة المتغيرات - Flowonline2", codeTitle: "📝 الكود المصدري - Flowonline2", closeTooltip: "إغلاق اللوحة", languageLabel: "اختر اللغة", activeVariables: "المتغيرات النشطة في الذاكرة", valueLabel: "القيمة:" },
    blocks: { main: "رئيسي", end: "نهاية", declare: "تعريف", assign: "تعيين", input: "إدخال", output: "إخراج", if: "إذا (If)", while: "طالما (While)", for: "من أجل (For)", do: "نفذ (Do)", call: "استدعاء", comment: "تعليق" },
    modals: { title: "تحرير الكتلة", cancel: "إلغاء", ok: "موافق", declareVar: "اسم المتغير(ات)", type: "النوع", isArray: "مصفوفة؟", arraySize: "حجم المصفوفة / البعد", assignTo: "اسم المتغير", expression: "تعبير", inputVar: "اسم المتغير", outputExpr: "تعبير (استخدم & للدمج)", newline: "سطر جديد؟", condition: "الشرط (تعبير منطقي)", forVar: "متغير الحلقة", start: "قيمة البداية", end: "قيمة النهاية", step: "الخطوة (الزيادة)", direction: "الاتجاه", ascending: "تصاعدي (أعلى)", descending: "تنازلي (أسفل)", callFunc: "اسم الدالة", arguments: "المعاملات (مفصولة بفواصل)", commentText: "نص التعليق", errorTypeMismatch: "القيمة لا تتطابق مع نوع المتغير.", errorRequired: "هذا الحقل مطلوب.", callFuncPlaceholder: "مثال: MyFunction", commentPlaceholder: "اكتب ملاحظاتك هنا...", blockCommentLabel: "ملاحظة/تعليق الكتلة (اختياري)", blockCommentPlaceholder: "مثال: تحقق من أن العمر > 18", declarePlaceholder: "مثال: x, y, sum", assignPlaceholder: "مثال: sum, arr[i]", inputPlaceholder: "مثال: x, arr[idx]", outputPlaceholder: "مثال: \"النتيجة: \" & sum" },
    errors: { executionError: "خطأ في التنفيذ", syntaxError: "خطأ نحوي في التعبير", varNotDefined: "المتغير غير معرف", typeMismatch: "عدم تطابق النوع", arrayIndexOutOfBounds: "فهرس المصفوفة خارج النطاق", divideByZero: "القسمة على صفر" },
    console: { title: "💬 وحدة تحكم التنفيذ - Flowonline2", clearBtn: "مسح", closeTooltip: "إغلاق اللوحة", emptyMessage: "وحدة التحكم فارغة. اضغط \"تشغيل\" لبدء الخوارزمية.", inputPlaceholder: "اكتب القيمة واضغط Enter...", submitBtn: "إرسال", readyStatus: "جاهز", logCount: "السجل: {0} سطر" },
    canvas: { selectBlock: "اختر كتلة" }
  },
  he: {
    title: "Flowonline2", subtitle: "שיבוט אינטראקטיבי של Flowgorithm",
    toolbar: { run: "הרץ", step: "צעד", pause: "השהה", stop: "עצור", speed: "מהירות", import: "פתח .fprg", export: "שמור .fprg", exportImage: "ייצא תמונה", exportJson: "גיבוי JSON", undo: "בטל", redo: "בצע שוב", clear: "נקה הכל" },
    sidebar: { variables: "צפייה במשתנים", codeGen: "קוד מקור", noVariables: "עדיין לא הוגדרו משתנים.", varName: "שם", varType: "סוג", varVal: "ערך", watchTitle: "👁️ צפייה במשתנים - Flowonline2", codeTitle: "📝 קוד מקור - Flowonline2", closeTooltip: "סגור חלונית", languageLabel: "בחר שפה", activeVariables: "משתנים פעילים בזיכרון", valueLabel: "ערך:" },
    blocks: { main: "ראשי", end: "סוף", declare: "הגדר", assign: "הקצה", input: "קלט", output: "פלט", if: "אם (If)", while: "כל עוד (While)", for: "עבור (For)", do: "בצע (Do)", call: "קריאה", comment: "הערה" },
    modals: { title: "ערוך בלוק", cancel: "ביטול", ok: "אישור", declareVar: "שם המשתנה(ים)", type: "סוג", isArray: "מערך?", arraySize: "גודל מערך / מימד", assignTo: "שם המשתנה", expression: "ביטוי", inputVar: "שם המשתנה", outputExpr: "ביטוי (השתמש ב-& לשרשור)", newline: "שורה חדשה?", condition: "תנאי (ביטוי בוליאני)", forVar: "משתנה הלולאה", start: "ערך התחלתי", end: "ערך סופי", step: "צעד (תוספת)", direction: "כיוון", ascending: "עולה (למעלה)", descending: "יורד (למטה)", callFunc: "שם הפונקציה", arguments: "ארגומנטים (מופרדים בפסיקים)", commentText: "טקסט ההערה", errorTypeMismatch: "הערך אינו תואם לסוג המשתנה.", errorRequired: "שדה זה נדרש.", callFuncPlaceholder: "לדוגמה: MyFunction", commentPlaceholder: "כתוב כאן את ההערות שלך...", blockCommentLabel: "הערת בלוק (אופציונלי)", blockCommentPlaceholder: "לדוגמה: בדוק שגיל > 18", declarePlaceholder: "לדוגמה: x, y, sum", assignPlaceholder: "לדוגמה: sum, arr[i]", inputPlaceholder: "לדוגמה: x, arr[idx]", outputPlaceholder: "לדוגמה: \"תוצאה: \" & sum" },
    errors: { executionError: "שגיאת ביצוע", syntaxError: "שגיאת תחביר בביטוי", varNotDefined: "המשתנה אינו מוגדר", typeMismatch: "אי התאמת סוגים", arrayIndexOutOfBounds: "אינדקס המערך מחוץ לטווח", divideByZero: "חלוקה באפס" },
    console: { title: "💬 מסוף ביצוע - Flowonline2", clearBtn: "נקה", closeTooltip: "סגור חלונית", emptyMessage: "המסוף ריק. לחץ \"הרץ\" כדי להתחיל את האלגוריתם.", inputPlaceholder: "הקלד ערך ולחץ Enter...", submitBtn: "שלח", readyStatus: "מוכן", logCount: "יומן: {0} שורות" },
    canvas: { selectBlock: "בחר בלוק" }
  },
  fa: {
    title: "Flowonline2", subtitle: "کلون تعاملی Flowgorithm",
    toolbar: { run: "اجرا", step: "گام به گام", pause: "توقف موقت", stop: "توقف", speed: "سرعت", import: "باز کردن .fprg", export: "ذخیره .fprg", exportImage: "خروجی تصویر", exportJson: "پشتیبان JSON", undo: "لغو", redo: "بازانجام", clear: "پاک کردن همه" },
    sidebar: { variables: "مشاهده متغیرها", codeGen: "کد منبع", noVariables: "هنوز متغیری تعریف نشده است.", varName: "نام", varType: "نوع", varVal: "مقدار", watchTitle: "👁️ مشاهده متغیرها - Flowonline2", codeTitle: "📝 کد منبع - Flowonline2", closeTooltip: "بستن پنل", languageLabel: "انتخاب زبان", activeVariables: "متغیرهای فعال در حافظه", valueLabel: "مقدار:" },
    blocks: { main: "اصلی", end: "پایان", declare: "تعریف", assign: "تخصیص", input: "ورودی", output: "خروجی", if: "اگر (If)", while: "تا وقتی (While)", for: "برای (For)", do: "انجام (Do)", call: "فراخوانی", comment: "نظر" },
    modals: { title: "ویرایش بلوک", cancel: "لغو", ok: "تأیید", declareVar: "نام متغیر(ها)", type: "نوع", isArray: "آرایه؟", arraySize: "اندازه آرایه / بعد", assignTo: "نام متغیر", expression: "عبارت", inputVar: "نام متغیر", outputExpr: "عبارت (از & برای الحاق استفاده کنید)", newline: "خط جدید؟", condition: "شرط (عبارت بولی)", forVar: "متغیر حلقه", start: "مقدار شروع", end: "مقدار پایان", step: "گام (افزایش)", direction: "جهت", ascending: "صعودی (بالا)", descending: "نزولی (پایین)", callFunc: "نام تابع", arguments: "آرگومان‌ها (جداشده با کاما)", commentText: "متن نظر", errorTypeMismatch: "مقدار با نوع متغیر مطابقت ندارد.", errorRequired: "این فیلد الزامی است.", callFuncPlaceholder: "مثال: MyFunction", commentPlaceholder: "یادداشت‌های خود را اینجا بنویسید...", blockCommentLabel: "یادداشت/نظر بلوک (اختیاری)", blockCommentPlaceholder: "مثال: بررسی کنید که سن > 18", declarePlaceholder: "مثال: x, y, sum", assignPlaceholder: "مثال: sum, arr[i]", inputPlaceholder: "مثال: x, arr[idx]", outputPlaceholder: "مثال: \"نتیجه: \" & sum" },
    errors: { executionError: "خطای اجرا", syntaxError: "خطای نحوی در عبارت", varNotDefined: "متغیر تعریف نشده است", typeMismatch: "عدم تطابق نوع", arrayIndexOutOfBounds: "شاخص آرایه خارج از محدوده", divideByZero: "تقسیم بر صفر" },
    console: { title: "💬 کنسول اجرا - Flowonline2", clearBtn: "پاک کردن", closeTooltip: "بستن پنل", emptyMessage: "کنسول خالی است. \"اجرا\" را فشار دهید تا الگوریتم شروع شود.", inputPlaceholder: "مقدار را تایپ کرده و Enter را فشار دهید...", submitBtn: "ارسال", readyStatus: "آماده", logCount: "گزارش: {0} خط" },
    canvas: { selectBlock: "انتخاب بلوک" }
  }
};
